### ISSUE TITLE
Re-introduce FAWE support

### ISSUE THREAD

**Issue by rlf** [rlf/uSkyBlock#1083]
We need to support some sort of Async-World-Edit again, unfortunately it isn't possible atm.

Current "state of FAWE" gives this when pasting:
```
[17:13:09 WARN]: java.lang.NullPointerException
[17:13:09 WARN]:        at com.boydti.fawe.jnbt.SchematicStreamer.readFully(SchematicStreamer.java:183)
[17:13:09 WARN]:        at com.boydti.fawe.jnbt.SchematicStreamer.getClipboard(SchematicStreamer.java:455)
[17:13:09 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:69)
[17:13:09 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:64)
[17:13:09 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.load(ClipboardFormat.java:529)
[17:13:09 WARN]:        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.load(ClipboardFormat.java:525)
[17:13:09 WARN]:        at us.talabrek.ultimateskyblock.handler.asyncworldedit.FAWEAdaptor.lambda$loadIslandSchematic$0(FAWEAdaptor.java:57)
[17:13:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:63)
[17:13:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:13:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:13:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:13:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:13:09 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[17:13:09 WARN]: [uSkyBlock] Plugin uSkyBlock v2.7.5-SNAPSHOT generated an exception while executing task 2425
java.lang.UnsupportedOperationException: TODO FIXME
        at com.boydti.fawe.jnbt.CorruptSchematicStreamer.recover(CorruptSchematicStreamer.java:100) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:73) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.SchematicReader.read(SchematicReader.java:64) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.load(ClipboardFormat.java:529) ~[?:?]
        at com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.load(ClipboardFormat.java:525) ~[?:?]
        at us.talabrek.ultimateskyblock.handler.asyncworldedit.FAWEAdaptor.lambda$loadIslandSchematic$0(FAWEAdaptor.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.jar:git-Paper-133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.jar:git-Paper-133]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
Should be fixed when FAWE fixes their end (i.e. implements the TODO).

**Comment by Muspah** [comment]
#1169
