### ISSUE TITLE
can't create new challenges

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#109]
I got the latest build and coped in my challenges.yml, which it barfed on.   
Deleted and let the plugin create it's on default, and began folding my changes in by hand.
Modifications to existing challenges - requirements and rewards - works fine.  
Adding my own new challenge causes it to fail to load. 

After some more testing, simplified to just changing the name of 'baker:'  to 'laker:' causes it to fail.

[08:39:06] [Server thread/ERROR]: [uSkyBlock] Invalid challenge Challenge{name='laker', type=PLAYER, requiredItems='354:5;+1 400:5;+1 357:128;+4', ran
k='Hard', resetInHours=20, displayItem=ItemStack{CAKE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=laker, lore=[Bake cakes, pumpkin pies, 
and cookies.]}}, takeItems=true, reward=Reward{itemReward=[ItemStack{GOLD_INGOT x 5}, ItemStack{DIAMOND x 1}], permissionReward='null', currencyReward=50, xpReward=100, rewardText='5 gold ingots, 1 diamond', commands=[]}, repeatReward=Reward{itemReward=[ItemStack{IRON_ORE x 2}, ItemStack{GOLD_INGOT x 1}], permissionReward='null', currencyReward=30, xpReward=15, rewardText='2 iron, 1 gold ingot', commands=[]}}
java.lang.NullPointerException
        at us.talabrek.ultimateskyblock.challenge.Challenge.getDisplayItem(Challenge.java:125) ~[uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.getItemStack(ChallengeLogic.java:325) ~[uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.populateChallengeRank(ChallengeLogic.java:413) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.populateChallengeRank(ChallengeLogic.java:384) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.SkyBlockMenu.displayChallengeGUI(SkyBlockMenu.java:651) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.challenge.ChallengesCommand.onCommand(ChallengesCommand.java:38) [uSkyBlock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-52c130f-89944c0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-52c130f-89944c0]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-52c130f-89944c0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-52c130f-89944c0]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-52c130f-89944c0]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
[08:39:06] [Server thread/ERROR]: null

**Comment by rlf** [comment]
The actual failing challenges.yml would help me.
It seems that the displayItem element is not valid.

**Comment by woolwind** [comment]
it was the cake - on the last test, I changed nothing but the 'b' in 'baker' from the working default baker challenge.  I changed it back to 'b' and the file loads.

**Comment by rlf** [comment]
Still, I doubt that is the issue, since the stack-trace indicates an invalid item-id for the challenge.

**Comment by rlf** [comment]
So, could you please pastebin the failing challenges.yml, and I'll take a look.

**Comment by rlf** [comment]
Dutchy did some extensive testing yesterday - and it seems it's the challenges that is not correctly reloaded on `/usb reload`.
A server-restart or a `/plugman reload uSkyBlock` will get the challenges working.

I will look into fixing the core-issue, but you can use the above work-around until then.

**Comment by woolwind** [comment]
can't reproduce.  Possibly something related to doing /usb reload instead of fully restarting the world?

**Comment by dutchy1001** [comment]
Changing challenges and doing /usb reload doesnt give any errors anymore in console and work fine. 

What I did notest was that challenges are saved when a player leaves the server, if in the meantime the command /usb reload has been executed the player will loose those challenges. They will loose the items needed for the challenge, but they keep the rewards given for that challenge. They can then complete the challenge again as it was the first time.

**Comment by dutchy1001** [comment]
Think this has been fixed, reopen if it reoccures
