### ISSUE TITLE
please support 1.13.2

### ISSUE THREAD

**Issue by yunalan** [rlf/uSkyBlock#1114]
2.7.6-RC5 does support 1.13.2

[09:18:32] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.7.6-201809101626 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at us.talabrek.ultimateskyblock.Settings.loadPluginConfig(Settings.java:143) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:988) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.2.jar:git-Paper-426]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-426]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-426]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_172]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.2.jar:git-Paper-426]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	... 11 more
[09:18:32] [Server thread/INFO]: [uSkyBlock] Disabling uSkyBlock v2.7.6-201809101626
[09:18:32] [Server thread/ERROR]: Error occurred while disabling uSkyBlock v2.7.6-201809101626 (Is it up to date?)
java.lang.NullPointerException: null
	at us.talabrek.ultimateskyblock.uSkyBlock.onDisable(uSkyBlock.java:198) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.2.jar:git-Paper-426]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.2.jar:git-Paper-426]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-426]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-426]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]

**Comment by yunalan** [comment]
i found problem
newest worldgurde build has some problem

**Comment by robgob** [comment]
Can you please let me know what the issue was:? I am also having a problem running uskyblock with latest world edit,. Should i downgrade?

**Comment by Muspah** [comment]
The latest uSkyBlock-release from SpigotMC resources is not going to work with any recent WorldEdit-build. The latest build from this repository should work with the new WorldEdit builds, but there are some reports that the latest versions from WorldEdit are unstable.

My local test environment is running:
uSkyBlock: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181121-1-83646d4.jar
WorldEdit/WorldGuard: https://oss.pellegrom.pt/tmp/
