### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MatChev04** [rlf/uSkyBlock#1144]
error:`[13:08:34 ERROR]: Error occurred while enabling ServInterface v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: dk/lockfuglsang/minecraft/command/BaseCommandExecutor
        at fr.cubolt.ServInterface2.ServInterface.onEnable(ServInterface.java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:747) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-72c2605-251a5b6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: dk.lockfuglsang.minecraft.command.BaseCommandExecutor
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-72c2605-251a5b6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        ... 17 more`

I have copy the code [https://github.com/rlf/bukkit-utils/blob/master/src/main/java/dk/lockfuglsang/minecraft/command/README.md](url) for create my commande but I have replace AbstractCommandExecutor by BaseCommandExecutor beacause AbstractCommandExecutor  no existe.
mycode : `@Override
	public void onEnable() {
		
		System.out.println("Plugin ServInterface ON");
		getServer().getPluginManager().registerEvents(new ServInterfaceListeners(this), this);
		
		BaseCommandExecutor mycmd = new BaseCommandExecutor ("mycmd", "myplugin.perm.mycmd", "main myplugin command");
        mycmd.add(new AbstractCommand("hello|h", "myplugin.perm.hello", "say hello to the player") {
            public boolean execute(CommandSender sender, String alias, Map<String, Object> data, String... args) {
                sender.sendMessage(new String[]{
                        "Hello! and welcome " + sender.getName(),
                        "I was called with : " + alias,
                        "I had " + args.length + " arguments: " + Arrays.asList(args)
                });
                return false;
            }
        });
        getCommand("shop").setExecutor(mycmd);
	}`

sorry for english

**Comment by MatChev04** [comment]
sorry I me fail
