### ISSUE TITLE
update and add support fawe world edit please

### ISSUE THREAD

**Issue by successed** [rlf/uSkyBlock#1146]
Please add fawe support.
and fix the errors..

[17:40:16] [Server thread/INFO]: [uSkyBlock] Enabling uSkyBlock v2.7.6-RC3
[17:40:16] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.7.6-RC3 (Is it up to date?)
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat, but interface was expected
	at us.talabrek.ultimateskyblock.island.IslandGenerator.lambda$getSchematicFile$0(IslandGenerator.java:127) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_191]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_191]
	at us.talabrek.ultimateskyblock.island.IslandGenerator.getSchematicFile(IslandGenerator.java:127) ~[?:?]
	at us.talabrek.ultimateskyblock.island.IslandGenerator.<init>(IslandGenerator.java:74) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1007) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[17:40:16] [Server thread/INFO]: [uSkyBlock] Disabling uSkyBlock v2.7.6-RC3
[17:40:16] [Server thread/ERROR]: Error occurred while disabling uSkyBlock v2.7.6-RC3 (Is it up to date?)
java.lang.NullPointerException: null
	at us.talabrek.ultimateskyblock.uSkyBlock.onDisable(uSkyBlock.java:198) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-474]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-474]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-474]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Muspah** [comment]
For FAWE support, see #1083.

Could you try to reproduce the problem while using the latest WorldEdit and WorldGuard build from EngineHub and the latest build of Ultimate Skyblock?

uSkyBlock: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181121-1-83646d4.jar
WorldEdit: http://builds.enginehub.org/job/worldedit
WorldGuard: http://builds.enginehub.org/job/worldguard

**Comment by Muspah** [comment]
See #1169
