### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by random1167** [rlf/uSkyBlock#1148]
```
[uSkyBlock] Task #528 for uSkyBlock v2.7.6-RC3 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at us.talabrek.ultimateskyblock.command.AdminCommand.<init>(AdminCommand.java:86) ~[uSkyBlock-bukkit1.13.jar:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.registerEventsAndCommands(uSkyBlock.java:1046) ~[uSkyBlock-bukkit1.13.jar:?]
        at us.talabrek.ultimateskyblock.uSkyBlock$1.run(uSkyBlock.java:242) ~[uSkyBlock-bukkit1.13.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.2.jar:git-Spigot-667bdd6-1b982fd]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 10 more
```
* server-log: https://pastebin.com/raw/AKDRS5jR

**Comment by Muspah** [comment]
Hi,

That's a known problem since WorldEdit refactored their code. The necessary changes are pulled into this repository, but since @rlf is nowhere to be found, it's impossible to push updates to BukkitDev and Spigot resources.

To fix this issue, use:
uSkyBlock: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181121-1-83646d4.jar
WorldEdit: http://builds.enginehub.org/job/worldedit
WorldGuard: http://builds.enginehub.org/job/worldguard

**Comment by Wferr** [comment]
@Muspah im having the same error with NoClassDefFoundError with those downloads, any ideas on how to fix? Thanks.

**Comment by Muspah** [comment]
Can you post the full log output for me please? Is it really the same NoClassDefFound on com.sk89q.worledit.Vector? That would be strange.
