### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by GunneR007** [rlf/uSkyBlock#1153]
Hello im have problem with commands when i type in /is nothing when i type /island
nothing no commands work i cant even type /is challenge 
but here are the plugins  im using

spigot 1.13.2
Vault 1.7.1-b91
uSkyBlock v2.7.6-RC3
multiverse 1.4
wourldguard latest one
worldedit latest one as well
 i need help

**Comment by Muspah** [comment]
Could you post your latest server logfile, typically 'latest.log' from the logs-directory in your server folder?

**Comment by GunneR007** [comment]
the file is to big so i left it in the zip folder i hope thats ok please fix this 
[2019-01-21-3.log.gz](https://github.com/rlf/uSkyBlock/files/2780745/2019-01-21-3.log.gz)

**Comment by BlackBeltPanda** [comment]
I don't see uSkyBlock loading at all in that log file. I do see BSkyBlock, however.

**Comment by GunneR007** [comment]
the funny thing is the it makes the folder
but the commands dont work

**Comment by GunneR007** [comment]
this is nutty

**Comment by GunneR007** [comment]
no that was the latest one

**Comment by GunneR007** [comment]
i will try again

**Comment by GunneR007** [comment]
thats the latest's one with uskyblock loaded

**Comment by GunneR007** [comment]
sry got confuse but yea thats the latest one with skyblock

**Comment by GunneR007** [comment]
the funny thing is i can see the commands they r in gray when trying them it dont work thats crazy

**Comment by GunneR007** [comment]
if u want ot come to my server and take a look u more then welcome to do so

**Comment by GunneR007** [comment]
here is a new latest one with uskyblock
[latest.log](https://github.com/rlf/uSkyBlock/files/2780929/latest.log)

**Comment by GunneR007** [comment]
there is an error
with u skyblock i just saw the err on the log file

**Comment by GunneR007** [comment]
[19:47:41] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.7.6-RC3 (Is it up to date?)
java.lang.NullPointerException: null
	at us.talabrek.ultimateskyblock.handler.VaultHandler.setupPermissions(VaultHandler.java:41) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:987) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot.jar:git-Spigot-518206a-917411f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-518206a-917411f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-518206a-917411f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot.jar:git-Spigot-518206a-917411f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot.jar:git-Spigot-518206a-917411f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214) [spigot.jar:git-Spigot-518206a-917411f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot.jar:git-Spigot-518206a-917411f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[19:47:41] [Server thread/INFO]: [Vault] Enabling Vault v1.7.1-b91

**Comment by GunneR007** [comment]
it has to do with uskyblock and vault

**Comment by Muspah** [comment]
I'd really appreciate it if you could keep it all in one message :)

Looks like Vault 1.7.1 incompatability indeed (#1151). Using Vault 1.5.6 should work for now, I will try to update uSkyBlock this week.

Vault download: https://dev.bukkit.org/projects/vault/files/894359

Please also use the latest uSkyBlock-build from this repository, download: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181121-1-83646d4.jar

**Comment by GunneR007** [comment]
ok but if i downgrade vault wouldn't this effect my other plugins

**Comment by Muspah** [comment]
That depends on the other plugins you're using, check the plugins description or just try it out. I'ts 1:17AM here at the moment and I really need to get to bed now ;)

**Comment by GunneR007** [comment]
ok sry didnt realize its that late where u at goon night then

**Comment by GunneR007** [comment]
im sorry to bug u but i try the old vault and nothing something the commands not working

**Comment by Muspah** [comment]
Hmm, thought that I used Vault 1.5.6 on my local test server the last time, but it was 1.7.1. If anyone has a basic server setup without a lot of other plugins and a log full of unrelated errors, I'd love to hear so I can reproduce the problem.

**Comment by GunneR007** [comment]
i can do that
ok

**Comment by GunneR007** [comment]
give me 5 min

**Comment by GunneR007** [comment]
i got it to say no permission enable here is the log with out errors i think
[latest.log](https://github.com/rlf/uSkyBlock/files/2783766/latest.log)

**Comment by GunneR007** [comment]
so it work with the lates worldedit and vault huh this is nutty but ok

**Comment by GunneR007** [comment]
i think it had to do with the version of worldedit i ahd even though it was the latest one

**Comment by GunneR007** [comment]
I found out the problems and it has nothing to do with vault 

world-guard Legacy 7.0 beta 2 this plugin  stops  uskyblock commands form working 

protocol-lib interferes with vault and uskyblock cause the problems with uskyblock take this out and the your plugins work with out errors with vault i feel your plugin protocol lib and world guard interferes with each other causing these problems

**Comment by GunneR007** [comment]
I found out the problems and it has nothing to do with vault 

world-guard Legacy 7.0 beta 2 this plugin  stops  uskyblock commands from working 

protocol-lib interferes with vault and uskyblock cause the problems with uskyblock take this out and the your plugins work with out errors with vault i feel your plugin protocol lib and world guard interferes with each other causing these problems 
 
everyone can get the new update of worldguard here: 
http://builds.enginehub.org/job/worldguard?branch=master 
this may fix the problem with uskyblock

however other plugins may stop working please backup all plugins and then test the new version 
of worldguard.

I am still getting the problem with commands are currently disable.
will do more research for this

edit: updateing world has no effect and still stops uskyblock from working

**Comment by GunneR007** [comment]
@Muspah any progress on an up date ?...

**Comment by Guns29** [comment]
@Muspah Hello i have a ? any news on an update anytime soon i would love to use uskyblock again thanks a bunch

**Comment by GunneR007** [comment]
@Muspah hi there i was wondering are you going to update uskyblock or r u giving up on it
