### ISSUE TITLE
Error enabling uSkyBlock with most up-to-date version

### ISSUE THREAD

**Issue by santafejay** [rlf/uSkyBlock#1165]
[00:37:49 ERROR]: Error occurred while enabling uSkyBlock v2.7.6-RC3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
at us.talabrek.ultimateskyblock.Settings.loadPluginConfig(Settings.java:143) ~[?:?]
at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:988) ~[?:?]
at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-571]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-571]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-571]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-571]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
... 11 more
[00:37:49 INFO]: [uSkyBlock] Disabling uSkyBlock v2.7.6-RC3
[00:37:49 ERROR]: Error occurred while disabling uSkyBlock v2.7.6-RC3 (Is it up to date?)
java.lang.NullPointerException: null
at us.talabrek.ultimateskyblock.uSkyBlock.onDisable(uSkyBlock.java:198) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-571]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-571]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.13.2.jar:git-Paper-571]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-571]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Muspah** [comment]
The latest version on the SpigotMC resources isn't the latest build from this repository unfortunately, and we're unable to push new updates. But you _can_ download the latest build here: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20190328-1-ec2a672.jar

That should include changes regarding to the WorldEdit vectoring updates. Can you try that one? :)

**Comment by santafejay** [comment]
That one just takes me to an ERR_FAILED website says it may be moved or down

**Comment by StormyIceLeopard** [comment]
I tried it and no good. I get the following error:

[13:00:00] [Server thread/INFO]: [uSkyBlock] Enabling uSkyBlock v2.7.6-RC3
[13:00:00] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.7.6-RC3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at us.talabrek.ultimateskyblock.Settings.loadPluginConfig(Settings.java:143) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:988) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [Spigot.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [Spigot.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [Spigot.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [Spigot.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214) [Spigot.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [Spigot.jar:git-Spigot-5629554-4c8327f]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	... 11 more

**Comment by Muspah** [comment]
Can you try the version linked above? That should include fixes for the WorldEdit vectoring changes.

**Comment by StormyIceLeopard** [comment]
Starts and works but crashes:

[15:01:10] [Server thread/INFO]: StormyIceLeopard issued server command: /pardon DarkKronicle
[15:01:14] [User Authenticator #3/INFO]: UUID of player DarkKronicle is c5b61a1d-820f-495b-b630-49b656be8b2f
[15:01:14] [Server thread/INFO]: [+] DarkKronicle has joined this server.
[15:01:16] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.StackOverflowError: null
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at java.io.BufferedWriter.<init>(BufferedWriter.java:109) ~[?:1.8.0_191]
	at java.io.BufferedWriter.<init>(BufferedWriter.java:88) ~[?:1.8.0_191]
	at com.google.common.io.Files.newWriter(Files.java:98) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.UserCache.c(UserCache.java:228) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.UserCache.getProfile(UserCache.java:163) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1379) ~[Spigot.jar:git-Spigot-5629554-4c8327f]
	at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:68) ~[?:?]
	at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:93) ~[?:?]
	at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:68) ~[?:?]
	at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:93) ~[?:?]
	at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:68) ~[?:?]

**Comment by StormyIceLeopard** [comment]
Determined it's just new players that cause this error.

**Comment by santafejay** [comment]
Yes it worked (sorry for late reply)

**Comment by StormyIceLeopard** [comment]
So this is still an issue for me.
For some random reason, I am not affected but every other player is.

**Comment by Muspah** [comment]
I'm not sure if this is related to uSkyblock or WorldEdit/WorldGuard. Is it possible to post a full server log, e.g. when you start the server, reproduce the issue and shutdown the server again?
