### ISSUE TITLE
HolographicDisplays fake armorstands vs. removing entities on restart

### ISSUE THREAD

**Issue by Muspah** [rlf/uSkyBlock#1202]
From the forums...

https://pastebin.com/raw/aRCywHV5

**Comment by Muspah** [comment]
10.07 20:58:27 [Server] Server thread/ERROR Could not pass event RestartIslandEvent to uSkyBlock v2.7.10-SNAPSHOT
10.07 20:58:27 [Server] INFO org.bukkit.event.EventException: null
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.command.island.RestartCommand.doExecute(RestartCommand.java:49) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:43) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:129) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.utils.command.BaseCommandExecutor.onCommand(BaseCommandExecutor.java:42) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:116) ~[?:?]
10.07 20:58:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:333) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClickRestartMenu(SkyBlockMenu.java:822) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClick(SkyBlockMenu.java:805) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:30) ~[?:?]
10.07 20:58:27 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2162) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:894) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:887) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
10.07 20:58:27 [Server] INFO Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_14_R1.Entity.bukkitEntity from class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand
10.07 20:58:27 [Server] INFO at com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand.getBukkitEntity(EntityNMSArmorStand.java:206) ~[?:?]
10.07 20:58:27 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.getNearbyEntities(CraftEntity.java:497) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.clearEntitiesNearPlayer(uSkyBlock.java:573) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.uSkyBlock.restartPlayerIsland(uSkyBlock.java:528) ~[?:?]
10.07 20:58:27 [Server] INFO at us.talabrek.ultimateskyblock.event.InternalEvents.onRestart(InternalEvents.java:31) ~[?:?]
10.07 20:58:27 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
10.07 20:58:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-4d2f30f-f1f3355]
10.07 20:58:27 [Server] INFO ... 38 more

**Comment by Muspah** [comment]
The main problem seems to be created by HolographicDisplays:

10.07 20:58:27 [Server] INFO Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.server.v1_14_R1.Entity.bukkitEntity from class com.gmail.filoghost.holographicdisplays.nms.v1_14_R1.EntityNMSArmorStand

I can't do anything about that specific issue, the folks at HD have to fix their implementation. I will take a look at our clearEntitiesNearPlayer code to add some extra error handling so at least it doesn't crash the island restart process.

**Comment by Muspah** [comment]
I'm going to remove the uSkyBlock#removeEntitiesNearPlayer() method, it's only called from within uSkyBlock#restartPlayerIsland(), and that's always going to call the chunk regenerator, which also clears all entities within the chunk.
