### ISSUE TITLE
uSkyBlock doesn't load

### ISSUE THREAD

**Issue by dorianxonic** [rlf/uSkyBlock#1256]
_Please paste the output from `/usb version` below_
```java
[05:44:51] [Server thread/WARN]: Unexpected exception while parsing console command "usb version"
org.bukkit.command.CommandException: Cannot execute command 'usb' in plugin uSkyBlock v2.8.7 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1152) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-199]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

_What steps will reproduce the problem?_
1. Install/Copy-paste into Plugins folder
2. Run the server
3. -

server-log: [pastebin](https://pastebin.com/4bb1QSZD)

**Comment by Muspah** [comment]
The interesting part of the logfile is around line 71. We're trying to hook into Vault (VaultHandler line 31) and get the registered permission service, but the response is empty (NULL).

**Comment by dorianxonic** [comment]
Can I do something to fix it?

**Comment by Muspah** [comment]
I'm not entirely sure if there's much that I can do for you at the moment. We're asking Vault for the Permissions service, and getting a NULL reply back. The error should be handled in a nicer way, but that's not going to make a difference in functionality, the problem still persists. 

It seems like Vault itself is having issues detecting your LuckPerms installation too:

[05:41:05] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.

I'm not experienced with LuckPerms 5 to be honest, we're still on LP4 because of the API changes.

**Comment by dorianxonic** [comment]
It must be the `disable-ops` option on LP. I'll try again with that disabled and report back.

**Comment by dorianxonic** [comment]
Tested with that option disabled.
Also tested latest luckperms 4 build, same issue.

**Comment by Muspah** [comment]
Hmm, the Vault logline about a backup permission system seems to be always there, even when succesfully registered.

To be honest, I'm not sure where this is going wrong exactly and if it's USB, Vault, LP or a combination of all. The uSkyBlock-code erroring in your logfile is a very common way to get the Vault permission API.

We've updated our server to LP5 at the moment, with the following LuckPerms config.yml working perfectly: https://gist.github.com/Muspah/ef99bef9e3fde165b0433cc1ac9d28bc

**Comment by dorianxonic** [comment]
```java
[01:06:22] [Server thread/WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.17.2.46 which is not a depend, softdepend or loadbefore of this plugin.
[01:06:22] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[01:06:22] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[01:06:22] [Server thread/INFO]: [Vault] Enabled Version 1.7.2-b107
[01:06:22] [Server thread/WARN]: [LuckPerms] Loaded class net.milkbowl.vault.permission.Permission from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.
[01:06:22] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[01:06:22] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[01:06:22] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.15.2-v3
[01:06:22] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Paper(Spigot) (git-Paper-199) : v1_15_R1 (Minecraft 1.15.2)
[01:06:22] [Server thread/INFO]: [BKCommonLib.Network] [BKCommonLib] [Network] Now using the ProtocolLib library to provide Packet Listener and Monitor support
[01:06:24] [Server thread/INFO]: [BKCommonLib] Bringing home the bacon since 2011!
[01:06:24] [Server thread/INFO]: [BKCommonLib] BKCommonLib version 1.15.2-v3 (build: 750) enabled! (1.473s)
[01:06:24] [Server thread/INFO]: [uSkyBlock] Enabling uSkyBlock v2.7.6-201809101626
[01:06:24] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.7.6-201809101626 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
	at us.talabrek.ultimateskyblock.Settings.loadPluginConfig(Settings.java:143) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:988) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:222) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-199]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-199]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	... 11 more
[01:06:24] [Server thread/INFO]: [uSkyBlock] Disabling uSkyBlock v2.7.6-201809101626
[01:06:24] [Server thread/ERROR]: Error occurred while disabling uSkyBlock v2.7.6-201809101626 (Is it up to date?)
java.lang.NullPointerException: null
	at us.talabrek.ultimateskyblock.uSkyBlock.onDisable(uSkyBlock.java:198) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-199]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Paper-199]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-199]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[01:06:24] [Server thread/INFO]: Preparing level "world"
```
I'll setup a test environment with just the USB dependencies but this is the result without Gringotts.

**Comment by dorianxonic** [comment]
Clean installation with just the USB dependencies: 
[Pastebin](https://pastebin.com/VW31GmrN)

**Comment by dorianxonic** [comment]
This is a Spigot 1.15.*1* test on the same clean conditions.
[Pastebin Spitog 1.15.1](https://pastebin.com/4EV4Sann)

**Comment by Muspah** [comment]
The last clean setups seems to be with an older version of USB, the exception thrown is related to a WorldEdit API change that has been fixed in late 2018. The latest USB version can be found here: https://www.uskyblock.ovh/downloads/release/uSkyBlock/uSkyBlock-2.8.7.jar

**Comment by dorianxonic** [comment]
The link you sent me works perfectly on a clean environment. Unfortunatelly it keeps giving me the "null" on my production server. Testing without Gringotts does work, which means it is a conflict from Gringotts.

**Comment by Muspah** [comment]
Alright, good to hear, thanks for testing it! I wouldn't call it a conflict, we're simply requesting the available API from Vault. It seems like Vault or Gringotts is doing strange things.
