### ISSUE TITLE
ArrayIndexOutOfBoundsException With 1.20.6

### ISSUE THREAD

**Issue by rynstwrt** [rlf/uSkyBlock#1304]
_Please paste the output from `/usb version` below_
```
[08:02:44 WARN]: Unexpected exception while parsing console command "usb version"
org.bukkit.command.CommandException: Cannot execute command 'usb' in plugin uSkyBlock v3.1.0-SNAPSHOT - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:164) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:964) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:949) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:521) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

_What steps will reproduce the problem?_
1. Occurs on server start.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: [https://pastebin.com/Nbd9GkxT](https://pastebin.com/Nbd9GkxT)

(Not following the template will result in closing the issue.)

### Additional Information
-  Paper version 1.20.6-137-master@bd5867a (2024-06-04T21:04:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
- All dependencies are installed.
- This is the main part of the error (see pastebin for more)
```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.utils.reflection.ReflectionUtil.getCraftBukkitVersion(ReflectionUtil.java:32) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.utils.nbt.CraftBukkitNBTTagger.getCraftItemStackClass(CraftBukkitNBTTagger.java:92) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.utils.nbt.CraftBukkitNBTTagger.addNBTTag(CraftBukkitNBTTagger.java:47) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.utils.nbt.NBTUtil.addNBTTag(NBTUtil.java:54) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.utils.util.ItemStackUtil.createItemsWithProbabilty(ItemStackUtil.java:42) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createReward(ChallengeFactory.java:113) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createChallenge(ChallengeFactory.java:64) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.challenge.Rank.<init>(Rank.java:31) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.challenge.ChallengeFactory.createRankMap(ChallengeFactory.java:125) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.challenge.ChallengeLogic.<init>(ChallengeLogic.java:70) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:769) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at uSkyBlock-3.1.0-SNAPSHOT.jar/us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:217) ~[uSkyBlock-3.1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[08:01:44 INFO]: [uSkyBlock] Disabling uSkyBlock v3.1.0-SNAPSHOT
```

**Comment by rynstwrt** [comment]
UPDATE: This only occurs on Paper, not Spigot.

**Comment by dubbz2** [comment]
Hey, I have the same issue. It worked fine on spigot however I just switched to paper and it broke completely. I have the exact same log. For me my server is 1.21.
