### ISSUE TITLE
Player Put On Another Player's Island

### ISSUE THREAD

**Issue by TheMattVid** [rlf/uSkyBlock#169]
Player A made an island yesterday. Player B made an island today, and he was put on player A's island with no build permissions. He told me that he used the common /is and grass block method to create his island. Nothing else happened before his creation of the island. There were no console errors when the island was created. Player B now always is brought to Player A's island when he goes to his island home. The region is still titled as being Player A's island. One last thing is that the island did reset. I believe Player A did make changes yesterday that aren't there anymore. I will try to get more information from Player A regarding what he did yesterday. This error is critical.

**Comment by dutchy1001** [comment]
This sound like an error that has been fixed in earlier versions. If you dont use the latest version (v2.0.1 RC1.64) then I recommend to update first.

**Comment by rlf** [comment]
Well, it sounds like some of the things fixed since RC1.62 - but at the same time, the "lastIsland" handling is one of the left-overs from #5  - Meaning errors as the one described above might occur.
I'll take a look more, and see if I can find a cause for the above issue.

**Comment by TheMattVid** [comment]
The version I was using was the newest one on "Travis" sometime around this time yesterday.

**Comment by dutchy1001** [comment]
4 updates in the last 24 hours "the last version" is not good enough if refering to versions.

**Comment by rlf** [comment]
/version uSkyBlock will always tell you what version you are using.

**Comment by TheMattVid** [comment]
Here's the order of island events.
I create an island. 415
Player mike creates an island. 1815
Player monky creates an island. 1821
Player monky joins mike's island.
Player film creates an island, 2318
Player monky leaves an island. 2455
Player monky creates an island. 2457
Player jjnn creates an island. 3356
Player home joins jjnn's island. 3442
Player cpt creates an island. 3623
Player cpt  joins ???'s island. (I see no console record of someone inviting him, but yet his island was cleared. WorldGuard still shows him as an island owner.)
Later on, error when film logs off.
Player blue creates an island. Overtakes mike's island and protection region.
Player mine creates an island. Overtakes monky's island, but monky still has protection.


Here is the error when film logged off:
[23:16:57] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to uSkyBlock vv2.0.1-RC1.59
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerList.disconnect(PlayerList.java:313) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:832) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.NetworkManager.l(NetworkManager.java:242) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:79) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot19.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.island.IslandInfo.getMembers(IslandInfo.java:168) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.hasIslandMembersOnline(uSkyBlock.java:1545) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.unloadPlayerData(uSkyBlock.java:916) ~[?:?]
	at us.talabrek.ultimateskyblock.event.PlayerEvents.onPlayerQuit(PlayerEvents.java:46) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	... 12 more

**Comment by TheMattVid** [comment]
Also, sometime between monky joining mike's island and leaving mike's island, mikelogged out and got a similar error.
[21:31:56] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to uSkyBlock vv2.0.1-RC1.59
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerList.disconnect(PlayerList.java:313) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:832) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.NetworkManager.l(NetworkManager.java:242) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:79) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot19.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.island.IslandInfo.getMembers(IslandInfo.java:168) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.hasIslandMembersOnline(uSkyBlock.java:1545) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.unloadPlayerData(uSkyBlock.java:916) ~[?:?]
	at us.talabrek.ultimateskyblock.event.PlayerEvents.onPlayerQuit(PlayerEvents.java:46) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	... 12 more

**Comment by TheMattVid** [comment]
Shortly afterward, mike logged back in and skyblock said that it was loading player data. It then was followed by this error:
[21:34:24] [Server thread/ERROR]: [uSkyBlock] ERROR: Failed to protect mikelytohappen's Island (mikelytohappen)
java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.island.IslandInfo.getMembers(IslandInfo.java:168) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.handler.WorldGuardHandler.setRegionFlags(WorldGuardHandler.java:85) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.handler.WorldGuardHandler.protectIsland(WorldGuardHandler.java:43) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.loadPlayerData(uSkyBlock.java:902) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.event.PlayerEvents.onPlayerJoin(PlayerEvents.java:40) [uSkyBlock.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:263) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:148) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot19.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by TheMattVid** [comment]
Finally, perhaps a minute later, mike types in /is info and gets the following error:
[21:37:49] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock vv2.0.1-RC1.59
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot19.jar:git-Spigot-13716d9-0899683]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot19.jar:git-Spigot-13716d9-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot19.jar:git-Spigot-13716d9-0899683]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.island.IslandInfo.getMembers(IslandInfo.java:168) ~[?:?]
	at us.talabrek.ultimateskyblock.island.IslandInfo.isParty(IslandInfo.java:326) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.doExecute(LevelCommand.java:34) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:40) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:31) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:109) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:59) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot19.jar:git-Spigot-13716d9-0899683]
	... 14 more

**Comment by rlf** [comment]
All of those issues stem from a corrupt island.yml file (no members registered, even though mike think he is on it).
It was fixed quite some releases a go - but unfortunately - corrupt files are not easily fixed.

**Comment by rlf** [comment]
If you dare do it, it might be resolved by a moderator doing `/usb register mike` while being within 10 blocks of the islands bedrock.

*Note:* On old versions of USB - this has been known to reset the island, so do a backup (using world-edit) before you try it out.

**Comment by TheMattVid** [comment]
My version of usb is from yesterday and I even allowed the config file to regenerate itself yesterday.

**Comment by dutchy1001** [comment]
@TheMattVid 
Pls start using pastebin and when refering to versions use the version numbers as "My version of usb is from yesterday" isnt telling anything as there were 4 releases

**Comment by TheMattVid** [comment]
I will take note to use pastepin in the future.

I do not have knowledge of exactly which version I downloaded yesterday, nor do I know how to find out. What I do know is that I got the newest version at the time, which IS telling something because as far as I can tell, the problems I am encountering do not seem to be the things addressed in the fixes between yesterday and today.

**Comment by dutchy1001** [comment]
The easiest way to keep a track on the version numbers you use (atleast how I do it) is when I download a plugin I rename to including the version number. Example you download uSkyblock, it is named "uSkyblock.jar" I rename it then to "uSkyblock v2.0.1 RC1.65". To rename the .jar doesn't influance the working of it. I do this with all my plugins. 

An other way of finding out is to read the log when the server starts, all plugins are listed to there with verison numbers.

**Comment by TheMattVid** [comment]
I went back to the beginning of my server log and discovered that the version I am using is 1.5.9. Hopefully this helps.

**Comment by dutchy1001** [comment]
can you post that log into pastebin
(I'll be gone in 5 minutes)

**Comment by TheMattVid** [comment]
Yes, I will turn all of my logs into pastebins.

**Comment by TheMattVid** [comment]
You want me to post the entire server's log?

**Comment by dutchy1001** [comment]
post it from start till atleast fully loaded(like when the first player logs in). I will look at then in the morning as I'm off to bed.

**Comment by TheMattVid** [comment]
As requested, the server start-up logs until the first player logs in.
http://pastebin.com/DtGU0yGr

**Comment by TheMattVid** [comment]
Additional information: going back to when I said Player cpt appeared to have an island, but also appeared to join another island since he typed "/is accept", I went to the region where Player cpt apparently has an island region, and there was no island there. Seemingly, Player cpt typed "/is accept" without anyone sending him and invite and it deleted his island and kept the region. This may have something to do with the cause. All I can say is, in order to effectively fix this problem with players being placed on existing island regions, the plugin must use a better method to check if an island is already being used by a player.

**Comment by TheMattVid** [comment]
More information. Player blue, who was on player mike's island did "/is reset" to start over. It told him to do "/is leave" to confirm. Instead of restarting, the leave functionality kicked into place and he left his own island. Afterward, he did "/is create" to start again, but this time he was put somewhere else, as if now it recognized Player mike's island. The only problem is that Player blue has a region on his new island, as well as his old island. The region on the old island didn't disappear when he left.

**Comment by TheMattVid** [comment]
One last update: everything has fallen apart. Pretty much every island has had another island on it. At one point, we got Player blue off of Player mike's island by having Player blue leave his own island, but someone else has gone on top a few hours later. Literally. An island formed right on top of his island, pushing his island down right below the bedrock. That was a peculiar sight to watch. This is all just testing my players are helping me out with, but hopefully we can get this resolved with all of this information.

**Comment by rlf** [comment]
The server logs you provide, indicates you are not using the latest skyblock release.
We had a "bad" release earlier, and it seems that is the one you have been testing.
Please update to at least RC1.64 - and re-test (preferably from scratch - since you most likely have a lot of corrupt island-data now).

**Comment by TheMattVid** [comment]
Yes. I will download the newest version and start the process over from scratch. Being that this has been a problem since the Talabrek days and no particular fixes lately have directly targeted this issue, I have doubts that the problem will be resolved, even if I was using a release classified as bad. My players and I will continue to keep an eye on this with the newest version.

**Comment by dutchy1001** [comment]
To me too this sounds very much that many of your island files, yml files and maybe even the world is corrupt.
I'm not sure if this is a possability but can you start all over, meaning new world and new files? Completely remove all the uSkyblock files, including world, download the latest here https://github.com/rlf/uSkyBlock/releases/latest and then restart the server to see if that is clearing the issue's. (back them up to a "backup folder" ofcourse)

**Comment by TheMattVid** [comment]
I already did that. All skyblock related files including the world, the uskyblock plugin folder,  multiverse's skyworld lines, and worldguard's skyworld file have been deleted. This is a clean test. Also, keep in mind that I did the same thing for version 1.59. I am currently using 2.1 and everything that I encounter will be solely because of this new version.

**Comment by rlf** [comment]
I understand your frustration @TheMattVid but it's really hard for us to "fix", if it's only occurring on your server :(

I really appreciate you taking some time to investigate this issue - because, if we find it, it will really help making the plugin more "usable".

**Comment by dutchy1001** [comment]
send me your server ip (you can do that In bukkit or spigot with a private message if you like) and I'll join the server to see.

**Comment by TheMattVid** [comment]
Well, I'm reset now, but if I encounter the problem under this new version, I will tell you it so you can see. My players will be on later creating/joining/restarting islands, so if this problem has a consistent cause, it will probably happen once the main crowd arrives.

**Comment by rlf** [comment]
Can you share your server address? Or is it not a publicly available server?

**Comment by TheMattVid** [comment]
It is. My server address is tmv.zone

**Comment by dutchy1001** [comment]
After being on the server I think with the lat update it is solved.

closing issue for now.
