### ISSUE TITLE
Unhandled exception executing command 'c' in plugin uSkyBlock v2.2-HF9b

### ISSUE THREAD

**Issue by suwonsarara** [rlf/uSkyBlock#258]
I was try to solve the problem, but I failed. First I could not create a island. so I download new plugins.
worldguard-6.0.0-beta-05
worldedit-bukkit-6.0
Vault1.5
and uSkyBlock v2.2-HF9b

is work when I create a island, but when I try to use /challenge, I still failed. I had search the problem in here, but is seem I have everything the it required. 
here is the log.

[23:16:55] [Server thread/INFO]: suwonsarara issued server command: /c
[23:16:55] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'c' in plugin uSkyBlock v2.2-HF9b
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1016) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:846) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.milkbowl.vault.item.Items
	at us.talabrek.ultimateskyblock.handler.VaultHandler.getItemName(VaultHandler.java:74) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.Challenge.getRequiredItems(Challenge.java:102) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.Challenge.getDisplayItem(Challenge.java:151) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.getItemStack(ChallengeLogic.java:372) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.populateChallengeRank(ChallengeLogic.java:460) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.populateChallengeRank(ChallengeLogic.java:431) ~[?:?]
	at us.talabrek.ultimateskyblock.SkyBlockMenu.displayChallengeGUI(SkyBlockMenu.java:703) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengesCommand.onCommand(ChallengesCommand.java:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.7.10-R0.1-SNAPSHOTBuild1544.jar:git-Spigot-1544]
	... 13 more

**Comment by dutchy1001** [comment]
when using a 1.79/10 Vault needs to be v1.4.1, due to the new added items for 1.8 it gives an error as it cant find those items.

**Comment by suwonsarara** [comment]
Thanks!

**Comment by suwonsarara** [comment]
another question... where can i check how much block per price on is land level?

**Comment by dutchy1001** [comment]
if you mean the amount of points each block gives then you need to look in the "levelConfig.yml"

I presume from your answer the problem is fixed?

**Comment by suwonsarara** [comment]
yes, thanky you ,help a lot
