### ISSUE TITLE
NoClassDefFoundError:  Using 2.2 for 1.7.10 and worldguard 6.0 beta 5

### ISSUE THREAD

**Issue by ProsperCraft** [rlf/uSkyBlock#267]
I get this right after booting for the first(and second) time.

[20:57:33 WARN]: [uSkyBlock] Task #5 for uSkyBlock v2.2 for 1.7.10 generated an exception
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/databases/ProtectionDatabaseException
        at us.talabrek.ultimateskyblock.uSkyBlock$1.run(uSkyBlock.java:203) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]

**Comment by rlf** [comment]
Try updating to the latest HF release (think the current is v2.2-HF9b).
That one should startup on both 1.8 and 1.7.10 servers, and be able to handle that missing exception.

**Comment by dutchy1001** [comment]
Also to remind you that if you use v2.2-HF9b on a 1.7 server to use Vault v1.41 as the new version of Vault is giving an error because it looks for the new added items of 1.8 that aren't there.

**Comment by ProsperCraft** [comment]
https://github.com/rlf/uSkyBlock/issues/268
