### ISSUE TITLE
Could not pass event PlayerDeathEvent  to uSkyBlock v2.2-HF9b

### ISSUE THREAD

**Issue by ProsperCraft** [rlf/uSkyBlock#268]
1.7.10
uSkyBlock v2.2-HF9b
Vault (1.4.1-b436)
WorldEdit (6.0;3342-78f975b9),
WorldGuard (6.0.0-beta-05.1569-)

I did /is restart and it deleted my island, I fell to the ground(have not added the mod that creates void yet) and died, then it tried to teleport me to my new island.

[07:54:01 ERROR]: Could not pass event PlayerDeathEvent to uSkyBlock v2.2-HF9b
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:382) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:547) [mw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:979) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) [mw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70069_a(EntityLivingBase.java:1153) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70069_a(EntityPlayer.java:1984) [yz.class:?]
        at net.minecraft.entity.Entity.func_70064_a(Entity.java:1113) [sa.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70064_a(EntityLivingBase.java:212) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:776) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:600) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) [jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:744) [?:1.7.0_51]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.PlayerDeathEvent.getKeepInventory()Z
        at us.talabrek.ultimateskyblock.event.ItemDropEvents.onDeathEvent(ItemDropEvents.java:44) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_51]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_51]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        ... 23 more
[07:54:01 INFO]: Goshen_Ithilien fell from a high place

**Comment by dutchy1001** [comment]
MCPC-Plus is not a Craftbukkit/Spigot were USB is build on

**Comment by ProsperCraft** [comment]
Other then this one console error, everything is working great.

**Comment by ProsperCraft** [comment]
You guys have done a FANTASTIC job with this plugin, I really love the ingame menu, especially the challenges.

**Comment by rlf** [comment]
Ready for test in v2.2-HF10

**Comment by ProsperCraft** [comment]
Fixed in HF10 thank you!
