### ISSUE TITLE
WG 5.9 doesn't work with v2.2-HF9b

### ISSUE THREAD

**Issue by alepalma** [rlf/uSkyBlock#270]
I have issues with creating an island or using the plugin at all.

The error I get is 

[18:25:14] [Server thread/ERROR]: Could not pass event InventoryClickEvent to uSkyBlock v2.2-HF9b
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-952179b-e87122e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-e87122e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin uSkyBlock v2.2-HF9b
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:246) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at us.talabrek.ultimateskyblock.SkyBlockMenu.onClick(SkyBlockMenu.java:1160) ~[?:?]
        at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:22) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-952179b-e87122e]
        ... 14 more
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;
        at us.talabrek.ultimateskyblock.handler.WorldGuardHandler.isIslandIntersectingSpawn(WorldGuardHandler.java:326) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.islandInSpawn(uSkyBlock.java:830) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.getNextIslandLocation(uSkyBlock.java:1173) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.createIsland(uSkyBlock.java:1127) ~[?:?]
        at us.talabrek.ultimateskyblock.command.island.CreateCommand.doExecute(CreateCommand.java:23) ~[?:?]
        at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:31) ~[?:?]
        at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:110) ~[?:?]
        at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
        at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:63) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:246) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at us.talabrek.ultimateskyblock.SkyBlockMenu.onClick(SkyBlockMenu.java:1160) ~[?:?]
        at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:22) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-952179b-e87122e]
        ... 14 more
[18:25:53] [Server thread/WARN]: [ColoredTags] Task #19 for ColoredTags v2.1.1 generated an exception
ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
        at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:394) ~[?:?]
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?]
        at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
        at com.gmail.filoghost.coloredtags.PermissionProvider.getGRoup(PermissionProvider.java:37) ~[?:?]
        at com.gmail.filoghost.coloredtags.ColoredTags.updateNametag(ColoredTags.java:114) ~[?:?]
        at com.gmail.filoghost.coloredtags.AutomaticTask$1.run(AutomaticTask.java:21) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-e87122e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

I attach here, the whole log just in case: http://pastebin.com/6K3TJzre

I'll leave my skype here just in case: alepalma__

**Comment by dutchy1001** [comment]
I can count already 4 other issue's before it is uSkyblocks turn. 
Update all your plugins that can be updated before you go further,
Spigot (important), 
Essentials v2.13.1(important), 
TabColorFix, 
NoCheatPlus is missing a lot of new stuff not added, 
Vault can go up to 1.5.2, 
ColoredTags.

Also there are lines about PermissionEX, is that upto date?

Make sure you get updated versions for 1.8 servers, you ,might want to look at some dev builds to get the latest available.
Post an other full log (with pastebin) when it's all updated.

**Comment by alepalma** [comment]
okay will do, thank you very much!

**Comment by alepalma** [comment]
I'm sure this will make me look stupid (hehe) but where can i download the latest version of spigot? can't find where (went to spigotmc.org then to download all i can find is BuildTools.jar)

**Comment by alepalma** [comment]
Here's the updated log: http://pastebin.com/npygW2eE

Once again, thank you VERY much for helping me, I really need some help.

**Comment by alepalma** [comment]
Here's another log: http://pastebin.com/TDt1A9jt

In the other one I forgot to use uSkyBlock, in this one I've tried, the error continues.

**Comment by DogsPaw** [comment]
If you want to Skype: dogs.paw I can give you a copy. Or show you how to obtain it yourself.

**Comment by rlf** [comment]
The error-log above indicates the following:
```
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;
```
Basically, it says "You are using the wrong version of WorldGuard".

**Comment by alepalma** [comment]
I updated worlguard and worldedit, here's the new log: http://pastebin.com/BUz3i4Cv

**Comment by rlf** [comment]
Your world-guard version is still 5.9 - and that is still the reason for the error.

**Comment by Seadragon91** [comment]
@alepalma 
Here you have an link
http://dev.bukkit.org/bukkit-plugins/worldguard/files/

**Comment by alepalma** [comment]
Thank you very much all of you! It's now solved, Once again thanks for the help.
