### ISSUE TITLE
Server Crash on new island creation

### ISSUE THREAD

**Issue by ATon2** [rlf/uSkyBlock#280]
Spigot Version: git-Spigot-ed3e3af-ee6d0fa
uSkyblock Version: v2.2-HF9b
Worldedit Version: 6.0.2-SNAPSHOT;3347-fe6717a0
Worldguard Version: 6.0.0-SNAPSHOT.1488

Following error:
http://pastebin.com/nc45yr4t

Been getting this error since earlier versions as well.

**Comment by dutchy1001** [comment]
you can update your WorldGuard [here](http://builds.enginehub.org/job/worldguard/6587), also there is a newer version of usb to be downloaded at the DevBukkit page [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/files/19-usky-block-v2-2-hf11/)

If the problem still happens post a full log on pastebin from start till error.

**Comment by ATon2** [comment]
Uploaded both of them to latest, error persists.
Here's the log: http://pastebin.com/7da0R0KC

**Comment by rlf** [comment]
Hi @ATon2 
The error you are experiencing, is coming from a bug in Bukkit.
We've seen it before, but only when a skyworld hasn't been correctly configured upon import.
If you use Multiverse, you should be able to do a `/mv remove skyworld` and then re-start your server.
The plugin will then re-import the world into Multiverse, and set the proper generator etc. 

The part of your huge log-file of interest is this:
```
java.lang.IllegalArgumentException: n must be positive
        at java.util.Random.nextInt(Random.java:300) ~[?:1.7.0_75]
        at net.minecraft.server.v1_8_R1.BiomeJungle.a(SourceFile:64) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.ChunkProviderGenerate.getChunkAt(SourceFile:472) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.generator.NormalChunkGenerator.getChunkAt(NormalChunkGenerator.java:51) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:268) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.Chunk.loadNearby(Chunk.java:970) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:68) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:720) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) ~[spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-ed3e3af-ee6d0fa]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
```
As you might notice, it's all happening in Bukkit code, no-where is uSkyBlock "at fault" - it's simply a bug when the generator tries to generate the chunk of the new island.

Please ensure that your world is using `uSkyBlock` as generator, and that you are using a recent release of Bukkit/CraftBukkit/Spigot.

**Comment by dutchy1001** [comment]
with no further input I assume this can be closed.

if problem still happens reopen or create a new issue
