### ISSUE TITLE
Problem with schematics...again  :|

### ISSUE THREAD

**Issue by alepalma** [rlf/uSkyBlock#284]
Well the problem is posted before was already solved it was problem with permissions, now the problem is: Certain groups can't create the island a message pops out "Could not create your island. Please contact a moderator". I checked the console and there were a bunch of errors

For example:

```
[08:31:07] [Server thread/INFO]: MrAnnoyingCookie issued server command: /is
[08:31:09] [Server thread/ERROR]: [uSkyBlock] Error creating island
java.lang.IllegalArgumentException: Unknown item: '' in '265:6 4:128  388:2 2:4'
        at us.talabrek.ultimateskyblock.util.ItemStackUtil.createItemList(ItemStackUtil.java:27) ~[uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.util.ItemStackUtil.createItemArray(ItemStackUtil.java:35) ~[uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.island.IslandGenerator.setChest(IslandGenerator.java:293) ~[uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.island.IslandGenerator.createIsland(IslandGenerator.java:47) ~[uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.createIsland(uSkyBlock.java:1128) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.island.CreateCommand.doExecute(CreateCommand.java:23) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:31) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:110) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:63) [uSkyBlock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:246) [spigot.jar:git-Spigot-952179b-e87122e]
        at us.talabrek.ultimateskyblock.SkyBlockMenu.onClick(SkyBlockMenu.java:1160) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:22) [uSkyBlock.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-952179b-e87122e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-952179b-e87122e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
```

I'm leaving the full log here : http://pastebin.com/ma6xjgrc

Since it said java.lang.IllegalArgumentException: Unknown item: '' in '265:6 4:128  388:2 2:4' I figured it had something to do with the items in the chests so i m leaving here the config of the chests: http://pastebin.com/q1kyNGEH

**Comment by dutchy1001** [comment]
is the schematic that been used "default" uSkyblock island or your own island? 

If your own, didnt you call it "island_default" instead od just "default"

**Comment by alepalma** [comment]
I changed the name just in case that the '_' would be generatin errors

**Comment by dutchy1001** [comment]
the '_' would not cause a problem, wrong names would, their case-sensitive when it goes for schematics.

**Comment by alepalma** [comment]
but i checked that and they re correctly typed!

**Comment by dutchy1001** [comment]
so you have a schematic called "default"?

**Comment by alepalma** [comment]
yes, i jsut erased the "island_" from all the schematics and from the perms

**Comment by rlf** [comment]
Well, it's both a bug in the config, but something we should probably handle as well in the plugin.
You have 2 spaces instead of one at one point.
Since we split the "list" on spaces, we get an empty-string '', which isn't a valid indication of an item.

**Comment by alepalma** [comment]
when i took the second space out, it started to work! so thank you very much! :D
