### ISSUE TITLE
Error during Rank Generation

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#369]
[12:24:14] [Craft Scheduler Thread - 19/WARN]: [uSkyBlock] Error during rank generation
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:1.8.0_05]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_05]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source) ~[?:1.8.0_05]
	at org.bukkit.configuration.MemorySection.mapChildrenKeys(MemorySection.java:712) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.configuration.MemorySection.getKeys(MemorySection.java:83) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at us.talabrek.ultimateskyblock.uuid.FilePlayerDB.getUUIDFromName(FilePlayerDB.java:32) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uuid.FilePlayerDB.getDisplayName(FilePlayerDB.java:56) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.util.PlayerUtil.getPlayerDisplayName(PlayerUtil.java:18) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.createIslandLevel(IslandLogic.java:226) ~[uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.generateTopTen(IslandLogic.java:205) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.command.admin.GenTopTenCommand$1.run(GenTopTenCommand.java:28) [uSkyBlock.jar:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_05]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

**Comment by mcraftpete** [comment]
ok so obviously I updated at the time dutchy was with me , and I had to downgrade as on login players that have been using server daily for ages had to relog before they could get to their island.
Not sure if any change has been made since then  but I am keen to get this error sorted as its starting to become more frequent.If you could let me know that would be great.

**Comment by mcraftpete** [comment]
also just to add I am on 1.8.7 now so still same error occurs

**Comment by dutchy1001** [comment]
this should be fixed in HF6d, we wait and see what it does on your server.

**Comment by mcraftpete** [comment]
just confirming the rank generation error is fixed in hf6d :)

**Comment by rlf** [comment]
Closing
