### ISSUE TITLE
Unable to save regions StorageException

### ISSUE THREAD

**Issue by LihP** [rlf/uSkyBlock#370]
Hey recently I have seen this a few times and it had me worried. The regions.yml disappears untill the next region update or creations occurs. I am not sure what would happen if the server was to restart before a region update occurs, maybe worldguard would save on it's disable event.
The other day I had a player complain that they had no build permissions for their island, I checked and the region didn't exist. I used the "usb island protect" command and it fixed it, I checked the regions.yml to make sure the total regions matched the total islands but I only had 90 regions for 2600 islands. Again thankfully I was able to run the command "usb island protectall" and it fixed it in 1 second.
Here is my version details and an error from the console:

[11:58:05 INFO]: UUID of player LCBhall is 26c7c73e-b234-4257-906a-6138a7252ff7
[11:58:05 INFO]: LCBhall[/99.XXX.XX.XXX:58596] logged in with entity id 656347 at ([world] 60.0, 78.0, -68.0)
[11:58:05 INFO]: LCBhall joined the game
[11:58:05 INFO]: Creating empty config: /home/lihp/us/skyblock/plugins/Essentials/userdata/26c7c73e-b234-4257-906a-6138a7252ff7.yml
[11:58:05 INFO]: [GAListener] Player: LCBhall has 0 votes
[11:58:07 INFO]: [uSkyBlock] Creating new player config!
[11:58:07 INFO]: [uSkyBlock] Creating player config Paths!
[11:58:12 INFO]: <Mersadies_> Welcome c:
[11:58:30 INFO]: LCBhall issued server command: /is
[11:58:32 INFO]: [uSkyBlock] New protected region created for LCBhall's Island by LCBhall
[11:58:32 INFO]: [uSkyBlock] Finished creating player island.
[11:58:37 INFO]: [WorldGuard] Region data changes made in 'skyworld' have been background saved
[11:58:37 WARN]: Unable to save regions
>       com.sk89q.worldguard.protection.managers.storage.StorageException: Failed to rename temporary regions file to /home/lihp/us/skyblock/plugins/WorldGuard/worlds/skyworld/regions.yml
>       at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.saveAll(YamlRegionFile.java:249) ~[worldguard-6.0.0-beta-05.jar:6.0.0-beta-05]
>       at com.sk89q.worldguard.protection.managers.RegionManager.save(RegionManager.java:110) ~[worldguard-6.0.0-beta-05.jar:6.0.0-beta-05]
>       at us.talabrek.ultimateskyblock.handler.WorldGuardHandler$1.run(WorldGuardHandler.java:193) [uSkyBlock%20(5).jar:?]
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-550ebac-7019900]
>       at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-550ebac-7019900]
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_65]
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_65]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

[12:21:40 INFO]: Name: uSkyBlock
[12:21:40 INFO]: Version: 2.3-HF3b
[12:21:40 INFO]: Description: Ultimate SkyBlock v2.3-HF3b-5ee95f-dev
[12:21:40 INFO]: ------------------------------
[12:21:40 INFO]: Server: CraftBukkit git-Spigot-550ebac-7019900 (MC: 1.8)
[12:21:40 INFO]: ------------------------------
[12:21:40 INFO]: Name: Vault
[12:21:40 INFO]: Version: 1.5.3-b37
[12:21:40 INFO]: ------------------------------
[12:21:40 INFO]: Name: WorldEdit
[12:21:40 INFO]: Version: 6.0;3342-78f975b9
[12:21:40 INFO]: ------------------------------
[12:21:40 INFO]: Name: WorldGuard
[12:21:40 INFO]: Version: 6.0.0-beta-05.1569-
[12:21:40 INFO]: ------------------------------

**Comment by rlf** [comment]
That exception, is most likely caused by you having the regions.yml file open in another editor.

We don't save the regions our selves, but asks WG to do it, if WG is not able to, it will output a message as the one above.

WG will save regions on exit - but since we've had some reports as the one you mentioned, we try to ask WG to save when we think it's about time - balanced, ofc. - in an effort to avoid too much CPU/lag.

**Comment by LihP** [comment]
The usb island protectall command just saved me again, the file regions.yml has about 20 islands and was 33k in size, ran protectall and it created 4230 island regions and the file is back to 1,750kb. I cannot see any sign of a crash, I assume my daily restart happened between one of the region saves and the one before had the error. I am still running 2.3-HF3b, not been keeping up with builds.
