### ISSUE TITLE
Challenges reset on login

### ISSUE THREAD

**Issue by CitoyenCharly** [rlf/uSkyBlock#371]
I add the commits of yesterday in my uSkyblock version and now the challenges of the players are reset when they login / logout.

**Comment by rlf** [comment]
Did you read the release-notes? It specifically stated, that that might be an issue.

**Comment by CitoyenCharly** [comment]
Is there any way to fix this without removing all the commits of yesterday?

**Comment by rlf** [comment]
Well, it's quite easy to "remove all the commits", but sure, the above commits should fix most of the issues.
If you wan't to "roll-back", simply do a
```
git checkout v2.3-HF5a
```
and recompile...

**Comment by CitoyenCharly** [comment]
I can't do that, since the begining of my server I translate the plugin with Eclipse (it was before the .po files). Thanks for the fix.

**Comment by rlf** [comment]
According to the license - you should share your version - perhaps other french-speaking server owners would prefer your version over the .po

**Comment by CitoyenCharly** [comment]
I can do that, but I put the name of my server in some translation.
I find another problem. If we invite a player who already owns an island, he loses his island but he's not invited on the new island.

[01:21:26] [Server thread/INFO]: mxlive24 issued server command: /is invite CitoyenCharly
[01:21:29] [Server thread/INFO]: CitoyenCharly issued server command: /is accept
[01:21:40] [Server thread/INFO]: CitoyenCharly issued server command: /is h
[01:21:47] [Server thread/INFO]: [uSkyBlock] Cleared island in 17.611 seconds
[01:21:47] [Server thread/WARN]: [uSkyBlock] Task #91840 for uSkyBlock vCielbloc generated an exception
java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.player.PlayerLogic.getPlayerInfo(PlayerLogic.java:39) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.getPlayerInfo(uSkyBlock.java:893) ~[?:?]
	at us.talabrek.ultimateskyblock.command.InviteHandler.addPlayerToParty(InviteHandler.java:134) ~[?:?]
	at us.talabrek.ultimateskyblock.command.InviteHandler$2.run(InviteHandler.java:113) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock$4.run(uSkyBlock.java:510) ~[?:?]
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler$1.run(WorldEditHandler.java:159) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
[01:21:53] [Server thread/INFO]: CitoyenCharly issued server command: /is h
[01:21:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock vCielbloc
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.player.PlayerLogic.getPlayerInfo(PlayerLogic.java:39) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.getPlayerInfo(uSkyBlock.java:893) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:38) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:31) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:117) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
	... 15 more

**Comment by rlf** [comment]
I can't debug on custom made deployments - the line-numbers doesn't match my repo.
Sorry.

**Comment by rlf** [comment]
Moved your "new finding" to a separate issue #372
