### ISSUE TITLE
Trying to delete island with no region

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#375]
Hi,
I got a crash with this error , on server restart I can see the players island which looks like starter and it had no region around it...
```
12:19:55] [Server thread/INFO]: loagudrun1 issued server command: /island restart
[12:19:55] [Server thread/WARN]: Trying to delete an island - with no WG region! (skyworld:3080.00,150.00,-9570.00)
[12:19:55] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin uSkyBlock v2.3-HF3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler.getRegion(WorldEditHandler.java:166) ~[?:?]
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler.unloadRegion(WorldEditHandler.java:182) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.postRestart(uSkyBlock.java:542) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.access$500(uSkyBlock.java:92) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock$6.run(uSkyBlock.java:565) ~[?:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.clearIsland(IslandLogic.java:100) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.restartPlayerIsland(uSkyBlock.java:562) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RestartCommand.doExecute(RestartCommand.java:29) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:42) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:33) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:116) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:64) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-8a983f9-e81edfc]
	... 14 more
[12:19:56] [Server thread/INFO]: [A1Auction] Auction has 2 sec remaining.
```

**Comment by rlf** [comment]
It sounds like the root-cause is the same as we've seen before on your server pete.

The above trace tells us why it fails, but not why that situation occurred.
The prime question is, "why didn't the island have a region". If you can paste the full server log to pastebin, we might be able to find the root-cause.

**Comment by woolwind** [comment]
I may have a lead on this issue. We  had all our regions disappear the other day. It turns out the worldguard regions file for skyworld had reset to default.   I am suspecting a race condition in worldguard. There was one of these messages '[WorldGuard] Region data changes made in 'skyworld' have been background saved'  just before a server restart.

I didn't notice this for a couple of days because regions get regenerated when players pop in. I only discovered it when I did a purge and started getting errors about deleting islands with no regions.

**Comment by mcraftpete** [comment]
http://pasted.co/325889d0

A paste from startup , you will see multiple of the same error rank generation.

**Comment by mcraftpete** [comment]
sorry its a different error to the one at start of this chat , but similar as still to do with regions :)

**Comment by dutchy1001** [comment]
No further input.
Closing this.
