### ISSUE TITLE
playernamedchagedevent error v2.3-HF6d

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#399]
[02:03:16] [Server thread/ERROR]: Could not pass event PlayerNameChangedEvent to uSkyBlock v2.3-HF6d
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at us.talabrek.ultimateskyblock.uuid.PlayerNameChangeManager.checkPlayer(PlayerNameChangeManager.java:46) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uuid.PlayerNameChangeManager.onPlayerJoin(PlayerNameChangeManager.java:34) [uSkyBlock.jar:?]
	at sun.reflect.GeneratedMethodAccessor453.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.player.PlayerLogic.renameTo(PlayerLogic.java:98) ~[?:?]
	at us.talabrek.ultimateskyblock.uuid.PlayerNameChangeListener.renamePlayer(PlayerNameChangeListener.java:37) ~[?:?]
	at us.talabrek.ultimateskyblock.uuid.PlayerNameChangeListener.onPlayerNameChange(PlayerNameChangeListener.java:27) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	... 23 more
[02:03:16] [Server thread/INFO]: Sup3rb0y136[/92.21.94.23:38504] logged in with entity id 236672 at ([world]122.5, 65.5, 1790.5)

**Comment by mcraftpete** [comment]
iame change , they then have no access to /is h etc , when I try to /is w player it says don't exist
http://pastebin.com/WUR08Xcz
This means any namechanges currently are causing a problem

**Comment by dutchy1001** [comment]
Player name has been fixed in  v2.3-HF7i.

Closed
