### ISSUE TITLE
addplayertoparty error

### ISSUE THREAD

**Issue by mcraftpete** [rlf/uSkyBlock#400]
This error seems to occur after an island restart or new island...

```
[03:50:55] [Server thread/INFO]: [uSkyBlock] Cleared island in 5.833 seconds
[03:50:55] [Server thread/WARN]: [uSkyBlock] Task #193237 for uSkyBlock v2.3-HF6d generated an exception
java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.command.InviteHandler.addPlayerToParty(InviteHandler.java:137) ~[?:?]
	at us.talabrek.ultimateskyblock.command.InviteHandler$2.run(InviteHandler.java:114) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock$4.run(uSkyBlock.java:518) ~[?:?]
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler$1.run(WorldEditHandler.java:159) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot.jar:git-Spigot-d2856ae-8f0f4ed]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
```

**Comment by dutchy1001** [comment]
When this error happens does it do anything on the server? Does it prevent the player of doing anything?
With a restart I can understand if there were players in the party that it could give an error message but the new created island shouldnt. You cant create an island untill you left a party.

**Comment by rlf** [comment]
Seems to appear due to a missing leader on the island:
https://github.com/rlf/uSkyBlock/blob/9ade2f9c9d4c0b5091abe1180020706762d41c2b/src/main/java/us/talabrek/ultimateskyblock/command/InviteHandler.java#L137

**Comment by dutchy1001** [comment]
this should be fixed too, if not let me know and we reopen it.
