### ISSUE TITLE
Could not pass PlayerDeathEvent

### ISSUE THREAD

**Issue by MeddlingMoose** [rlf/uSkyBlock#407]
This happens quite a few times a day. Though it is the only error message I'm getting from uSkyblock. I'm not sure what causes it, or how to stop it - so any insight on this would be great!

Thanks :) and great work with the plugin!

-Moose

Console Output:

[15:14:57] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to uSkyBlock v2.3-HF3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:382) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:811) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityMonster.r(EntityMonster.java:72) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PathfinderGoalMeleeAttack.e(SourceFile:122) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.PathfinderGoalSelector.a(PathfinderGoalSelector.java:91) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityInsentient.doTick(EntityInsentient.java:473) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1625) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityMonster.m(EntityMonster.java:20) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1486) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntityMonster.t_(EntityMonster.java:24) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.EntitySpider.t_(EntitySpider.java:36) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:789) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.event.ItemDropEvents.addDropInfo(ItemDropEvents.java:64) ~[?:?]
	at us.talabrek.ultimateskyblock.event.ItemDropEvents.onDeathEvent(ItemDropEvents.java:58) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor517.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot187.jar:git-Spigot-3ccbe77-a6a57a9]
	... 28 more

**Comment by dutchy1001** [comment]
We are aware of this and hopefully will be fixed in the next release.

**Comment by MeddlingMoose** [comment]
Thank you @dutchy1001 for the quick response! When's the next release going to be out? :)

**Comment by dutchy1001** [comment]
not sure as our last test (today) did not met our standards for release

**Comment by MeddlingMoose** [comment]
@dutchy1001 ah, okay thank you. Would you say it is coming soon? A ballpark? ^-^
(also... quick question while I have this ticket/issue thing open - what's the permission for bypassing the /island home teleport time I haven't been able to find it anywhere)

**Comment by dutchy1001** [comment]
You can give the perm "usb.mod.bypasscooldowns" (the permission is now added to the [bukkit](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/commands-and-permissions/#w-the-moderator-permissions) page) or set a different time in the config.yml (islandTeleportDelay: X)

**Comment by MeddlingMoose** [comment]
Has there been any progress towards a new release fixing this issue yet? :)

**Comment by dutchy1001** [comment]
this should be fixed in the pre-releases (v2.3-HF8d)
