### ISSUE TITLE
Item Rewards not working

### ISSUE THREAD

**Issue by FlamesRunner** [rlf/uSkyBlock#435]
Unique identifier: ff9363a0-2701-4846-9fe6-4c578da0e510
Java version: 
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.3.el6_6-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
Plugin Version: uSkyBlock v2.3-HF3
Server Version: Spigot 1.8.3 R0.1 Snapshot 
Server is in online mode.
CentOS release 6.6 (Final)
Quad-Core AMD Opteron(tm) Processor 1381 @ 2512.937MHZ per core
3 players online.

---

It appears that uSkyBlock broadcasts the message onto the server, but does not reward the user with the given items.

The configuration for uSkyBlock has not been modified.

**Comment by dutchy1001** [comment]
All the info is great but not what we normally want, System specs are fine for any server to run but we really like the depended plugin versions. Please do" /usb version" and post those details if you can

**Comment by FlamesRunner** [comment]
6.00-beta-05.1569 is the version of uSkyBlock.
The system has 3GB of RAM.

**Comment by FlamesRunner** [comment]
[23:07:15 INFO]: Name: uSkyBlock
[23:07:15 INFO]: Version: 2.3-HF3
[23:07:15 INFO]: Description: Ultimate SkyBlock v2.3-HF3-9fc81a-dev
[23:07:15 INFO]: ------------------------------
[23:07:15 INFO]: Server: CraftBukkit git-Spigot-dbe012b-61ef214 (MC: 1.8.3)
[23:07:15 INFO]: ------------------------------
[23:07:15 INFO]: Name: Vault
[23:07:15 INFO]: Version: 1.5.3-b37
[23:07:15 INFO]: ------------------------------
[23:07:15 INFO]: Name: WorldEdit
[23:07:15 INFO]: Version: 5.6
[23:07:15 INFO]: ------------------------------
[23:07:15 INFO]: Name: WorldGuard
[23:07:15 INFO]: Version: 6.0.0-beta-05.1569-
[23:07:15 INFO]: ------------------------------

The system has 3GB of RAM.

**Comment by dutchy1001** [comment]
I see the problem, dont mix v5 and v6 from WE and WG. this is mentioned on the wiki here and on our bukkit page.
Suggestion:
Update spigit to 1.8.7
update WE to 6.1 or dev build
update WG to 6.1 or dev build

Linkd for WE and WG can be found on our bukkit page [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/)

**Comment by FlamesRunner** [comment]
Thanks for the help!

**Comment by FlamesRunner** [comment]
It doesn't appear that the issue was fixed.
I receive the error every time someone attempts to complete a challenge:

org.bukkit.command.CommandException: Unhandled exception executing command 'challenge' in plugin uSkyBlock v2.3-HF3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-74e8786-a3cb1bc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-74e8786-a3cb1bc]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1149) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:984) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [server.jar:git-Spigot-74e8786-a3cb1bc]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
        at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.completeChallenge(ChallengeLogic.java:89) ~[?:?]
        at us.talabrek.ultimateskyblock.challenge.ChallengesCommand.onCommand(ChallengesCommand.java:91) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-74e8786-a3cb1bc]
        ... 15 more

**Comment by dutchy1001** [comment]
please do /usb version again (and post here) as it seems something has not been updated

**Comment by FlamesRunner** [comment]
[15:23:22 INFO]: ------------------------------
[15:23:22 INFO]: Server: CraftBukkit git-Spigot-74e8786-a3cb1bc (MC: 1.8.7)
[15:23:22 INFO]: ------------------------------
[15:23:22 INFO]: Name: Vault
[15:23:22 INFO]: Version: 1.5.3-b37
[15:23:22 INFO]: ------------------------------
[15:23:22 INFO]: Name: WorldEdit
[15:23:22 INFO]: Version: 6.1;no_git_id
[15:23:22 INFO]: ------------------------------
[15:23:22 INFO]: Name: WorldGuard
[15:23:22 INFO]: Version: 6.1
[15:23:22 INFO]: ------------------------------

**Comment by FlamesRunner** [comment]
Seems to be fixed; I found the issue.
iConomy was present and was colliding with Essentials.
Thanks!

**Comment by dutchy1001** [comment]
nice one, thx for letting us know.
