### ISSUE TITLE
Internal Error Once Executing /island create! (edit admin)

### ISSUE THREAD

**Issue by oriamrm** [rlf/uSkyBlock#442]
Whenever I'm Trying To Create An Island, It Tells Me That An Internal Error Has occurred!
Please Help!

I'm Using Spigot 1.8
uSkyBlock 2.3-HF3
WorldEdit 6.1
WorldGuard 6.1
MultiVerse Core 2.5
MultiVerse Portals 2.5

Full Error:
[01:13:11 INFO]: oriamrm issued server command: /island create
[01:13:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'isla
nd' in plugin uSkyBlock v2.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:640) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerCon
nection.java:1162) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:997) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:45) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:1) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spig
ot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
14) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
53) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:556) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.
ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/L
ist;
        at us.talabrek.ultimateskyblock.handler.WorldGuardHandler.isIslandInters
ectingSpawn(WorldGuardHandler.java:326) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.islandInSpawn(uSkyBlock.java:8
40) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.getNextIslandLocation(uSkyBloc
k.java:1183) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.createIsland(uSkyBlock.java:11
37) ~[?:?]
        at us.talabrek.ultimateskyblock.command.island.CreateCommand.doExecute(C
reateCommand.java:23) ~[?:?]
        at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.exec
ute(RequirePlayerCommand.java:31) ~[?:?]
        at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execu
te(CompositeUSBCommand.java:116) ~[?:?]
        at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.o
nCommand(AbstractCommandExecutor.java:21) ~[?:?]
        at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCo
mmand.java:64) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got_server.jar:git-Spigot-f94fe8f-d27e6d0]
        ... 15 more

**Comment by dutchy1001** [comment]
Instead of shouting in caps for help you should have read [this section](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) of the main page first. 
Follow those guide lines to post an issue and I'm glad to help out

**Comment by oriamrm** [comment]
Sorry.
I'm Pretty New To GitHub And I Didn't Knew There Were Roles.

Anyway I Solved My Problem, I Just Updated WorlEdit And WorldGuard. I Saw That I Need To Do It In The GitHub Tutarial, So I Think You Should Write It In Bukkit To.

Sorry & Thanks

**Comment by dutchy1001** [comment]
np glad it's sorted now
