### ISSUE TITLE
[SOLVED] /is create ISSUE!

### ISSUE THREAD

**Issue by OfficialJoe** [rlf/uSkyBlock#447]
[15:18:56] [Server thread/INFO]: OfficialJoe issued server command: /is create
[15:18:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.3-HF1c
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedCuboidRegion.getIntersectingRegions(Ljava/util/Collection;)Ljava/util/List;
	at us.talabrek.ultimateskyblock.handler.WorldGuardHandler.isIslandIntersectingSpawn(WorldGuardHandler.java:328) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.islandInSpawn(uSkyBlock.java:847) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.getNextIslandLocation(uSkyBlock.java:1190) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.createIsland(uSkyBlock.java:1144) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.CreateCommand.doExecute(CreateCommand.java:25) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:33) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:116) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:64) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 15 more
[15:18:58] [Server

**Comment by dutchy1001** [comment]
no further input then a log, Check the "caused by" line and read the [Bukkit](http://dev.bukkit.org/bukkit-plugins/uskyblock/) page

**Comment by OfficialJoe** [comment]
@dutchy1001 What do you mean by read the Bukkit page? Do I need to post it there or what :$

**Comment by OfficialJoe** [comment]
FIXED! I installed newest version of WG & WE.

**Comment by dutchy1001** [comment]
I guess the reading of the bukkit page helped here then
