### ISSUE TITLE
Island Generation Issue

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#486]
Hi there.

I recently just updated to the latest version of the plugin, and now whenever new players create their island, or when old players restart their island, they get the following error.

```
26.09 15:21:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
26.09 15:21:22 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
26.09 15:21:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_79]
26.09 15:21:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_79]
26.09 15:21:22 [Server] INFO at us.talabrek.ultimateskyblock.event.MenuEvents.guiClick(MenuEvents.java:22) ~[?:?]
26.09 15:21:22 [Server] INFO at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.onClick(SkyBlockMenu.java:782) ~[?:?]
26.09 15:21:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:242) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin uSkyBlock v2.4.3
26.09 15:21:22 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_79]
26.09 15:21:22 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_79]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-76236cb-c373061]
26.09 15:21:22 [Server] INFO org.bukkit.event.EventException
26.09 15:21:22 [Server] INFO [15:21:22 ERROR]: Could not pass event InventoryClickEvent to uSkyBlock v2.4.3
```

If they try to re-click it, it tells them that their island is generating, yet, nothing is happening. Relogs and/or restarts don't fix it.

**Comment by rlf** [comment]
No such version as "the latest" m8.
Please provide the info shown in `/usb version`.

**Comment by rlf** [comment]
Verified. Reproduced on v2.4.3

**Comment by rlf** [comment]
Could you please share the version info, esp. reg. your language.
It seems that might have been the root-cause.

**Comment by rlf** [comment]
Going out a limb here, and saying that you used `/usb lang <language>`.

A work-around (till next release), is to use `/usb reload` when-ever you use the above command.
