### ISSUE TITLE
AWE Handler Error

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#500]
Getting this error after updating to the latest AWE.

[16:41:31 WARN]: [uSkyBlock] Task #8 for uSkyBlock v2.4.6 generated an exception
java.lang.NoClassDefFoundError: org/primesoft/asyncworldedit/utils/FuncParamEx
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_45]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_45]
	at us.talabrek.ultimateskyblock.handler.AsyncWorldEditHandler.getAWEAdaptor(AsyncWorldEditHandler.java:59) ~[?:?]
	at us.talabrek.ultimateskyblock.handler.AsyncWorldEditHandler.onEnable(AsyncWorldEditHandler.java:29) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock$2.run(uSkyBlock.java:227) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-06ad352-4a7472d]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot.jar:git-Spigot-06ad352-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot.jar:git-Spigot-06ad352-4a7472d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot.jar:git-Spigot-06ad352-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot.jar:git-Spigot-06ad352-4a7472d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot.jar:git-Spigot-06ad352-4a7472d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: org.primesoft.asyncworldedit.utils.FuncParamEx
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot.jar:git-Spigot-06ad352-4a7472d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-06ad352-4a7472d]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
	... 12 more

**Comment by rlf** [comment]
Please provide the output of `/usb version`.
This is most likely related to the AWE version you are using.

**Comment by rlf** [comment]
Should be fixed in v2.4.7 - i.e. when AWE breaks our compatibility, we just revert to not using AWE.

**Comment by dutchy1001** [comment]
tested and fixed in v2.4.7
