### ISSUE TITLE
[Bug] /is restart do not work

### ISSUE THREAD

**Issue by Kaladial** [rlf/uSkyBlock#513]
Hi 

i got an error when i will restart an island:

[12:31:16] [Server thread/INFO]: Vala_Mal_Doran issued server command: /is restart
[12:31:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.4.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/extent/Extent
	at us.talabrek.ultimateskyblock.island.IslandLogic.clearIsland(IslandLogic.java:158) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.restartPlayerIsland(uSkyBlock.java:458) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RestartCommand.doExecute(RestartCommand.java:39) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:42) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:122) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	... 15 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.extent.Extent
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_72]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_72]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	at us.talabrek.ultimateskyblock.island.IslandLogic.clearIsland(IslandLogic.java:158) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.restartPlayerIsland(uSkyBlock.java:458) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RestartCommand.doExecute(RestartCommand.java:39) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:42) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:122) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_sky.jar:git-Spigot-2ec6f06-7722428]
	... 15 more

can you help me?

**Comment by rlf** [comment]
If you provide us with output from `/usb version` we can try.

**Comment by Kaladial** [comment]
uSkyBlock 2.4.7 (the Problem is at version v2.3-HF3 then i updated the version 2.4.4 -> 2.4.6 -> 2.4.7 but the problem is on all versions)

Vault 1.5.3-b37
WorldEdit 5.6.3
WorldGuard 6.1

**Comment by Kaladial** [comment]
ah ok i have update the worldedit and now is running
