### ISSUE TITLE
is restart on 1.7.10 v2.4.9

### ISSUE THREAD

**Issue by devryb** [rlf/uSkyBlock#541]
Using is restart on the 1.7 version the island never restarts and players get an internal error has occured message on their client.

Server plugins:
Worldguard 6.1
Worldedit 6.1
uskyblock 2.4.9
Vault 1.4.1

The following error is shown in the server log when this happens:
```
[11:48:38] [Server thread/INFO]: devryb issued server command: /is restart
[11:48:40] [Server thread/INFO]: devryb issued server command: /is restart
[11:48:40] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.4.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1448.150]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1448.150]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1448.150]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NoSuchMethodError: org.bukkit.scheduler.BukkitScheduler.runTask(Lorg/bukkit/plugin/Plugin;Lorg/bukkit/scheduler/BukkitRunnable;)Lorg/bukkit/scheduler/BukkitTask;
	at us.talabrek.ultimateskyblock.handler.WorldEditHandler.clearIsland(WorldEditHandler.java:201) ~[?:?]
	at us.talabrek.ultimateskyblock.island.IslandLogic.clearIsland(IslandLogic.java:158) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.restartPlayerIsland(uSkyBlock.java:459) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RestartCommand.doExecute(RestartCommand.java:39) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:42) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.CompositeUSBCommand.execute(CompositeUSBCommand.java:122) ~[?:?]
	at us.talabrek.ultimateskyblock.command.common.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:21) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1448.150]
	... 13 more
```

**Comment by rlf** [comment]
Please provide the output (copy paste from console) of `/usb version`.
Some of the details in there will help us.

**Comment by dutchy1001** [comment]
I just started a 1.7.10 server with the same depended plugins but restart is fine. No error in console

**Comment by devryb** [comment]
usb version info: http://puu.sh/l9DYx/3684a8bd5c.png
Server log: https://gist.github.com/devryb/40a571734fb3d98573e6

**Comment by csorrows** [comment]
Maybe the difference is in java versions? Just a guess.

**Comment by dutchy1001** [comment]
No, they fail to tell in the first message that they use Kcauldron, which in my opinion is one of the first things they should do to eliminate issue's as it is not tested by us on that. So spending time to recreate an issue with the wrong server files is then totally useless.

**Comment by rlf** [comment]
It seems the KCauldron v1.7.10 is based on v1.7.9 - that means, it doesn't have the same methods as we use from the v1.7.10 bukkit interfaces.

I will create a bukkit-1.7.9 branch, and try to make a version of v2.5.3 that is 1.7.9 compatible - no /usb config, no rabbits etc :D

**Comment by csorrows** [comment]
I think this would be the best direction to go in. I have seen this issue come up quite a few times. The ticket creators should realize they are using a server environment that is not that common and because of that, could cause issues with everything.

**Comment by rlf** [comment]
Try out this one https://github.com/rlf/uSkyBlock/releases/download/v2.5.3-bukkit-1.7.9/uSkyBlock.jar

**Comment by devryb** [comment]
Thanks for that, my apologies I was only thinking the worldedit, worldguard and Vault versions were what mattered.

Unfortunately it looks like this one won't load:

[18:53:44] [Server thread/INFO]: [uSkyBlock] Enabling uSkyBlock v2.5.3-bukkit-1.7.9
[18:53:44] [Server thread/INFO]: No plugins\uSkyBlock\config.yml found, it will be created
[18:53:44] [Server thread/INFO]: [uSkyBlock] 0 schematics loaded.
[18:53:44] [Server thread/INFO]: No plugins\uSkyBlock\challenges.yml found, it will be created
[18:53:44] [Server thread/ERROR]: Error occurred while enabling uSkyBlock v2.5.3-bukkit-1.7.9 (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.from(Ljava/lang/String;)Lguava10/com/google/common/cache/CacheBuilder;
	at us.talabrek.ultimateskyblock.challenge.ChallengeCompletionLogic.<init>(ChallengeCompletionLogic.java:36) ~[?:?]
	at us.talabrek.ultimateskyblock.challenge.ChallengeLogic.<init>(ChallengeLogic.java:63) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1154) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:216) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1448.150]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1448.150]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1448.150]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1448.150]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1448.150]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
