### ISSUE TITLE
org.codehaus.mojo:exec-maven-plugin:1.3.2:exec fails with Process exited with an error: 128

### ISSUE THREAD

**Issue by vk2gpz** [rlf/uSkyBlock#542]
build process fails at uSkyBlock-Core:

```
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uSkyBlock-Core: Command execution failed. Process exited with an error: 128 (Exit value: 128) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default) on project uSkyBlock-Core: Command execution failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:303)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:402)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:164)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:767)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:283)
	... 22 more
```

**Comment by dutchy1001** [comment]
"Tittle" is mostly used for a subject tittle, not a whole explanation of the problem.

**Comment by rlf** [comment]
I assume you are trying to build the latest (bleeding edge - master) of uSkyBlock?

**Comment by vk2gpz** [comment]
yes.  or should I clone different version?

**Comment by rlf** [comment]
No, but just for the record. The info you gave us, even though it takes up a lot of space, all it really says is "Compile failed".

I assume there were something more sensible in the output than that?

**Comment by vk2gpz** [comment]
no, that's the best information i can see from the maven console output.  That's why I came here to seek help.  I thought exec-maven-plugin was trying to execute something and failing but I could not see any information about what exec-maven-plugin is trying to do.  I've done -e, -X options but the information I provided was the best I can get from those options.

**Comment by vk2gpz** [comment]
i've re-cloned the latest and it compiled.

**Comment by rlf** [comment]
You haven't installed gettext properly.
See https://github.com/rlf/uSkyBlock/wiki/Building

But, with the latest changes, gettext shouldn't be mandatory anymore.

I will push some changes allowing you to build without it.

**Comment by vk2gpz** [comment]
odd, i do have gettext/xgettext installed and working. but if you can put something which remove gettext dependency, that would be much appreciated.

**Comment by rlf** [comment]
Latest commit 87339f3 moves po-generation (gettext dependency) to be hidden behind `-Pi18n`

**Comment by vk2gpz** [comment]
tx, will try that.
