### ISSUE TITLE
Error with /is command

### ISSUE THREAD

**Issue by MrFiliper** [rlf/uSkyBlock#573]
If player use command /is, display this error. Whats is wrong?

INFO

> [22:31:43 INFO]: Název: uSkyBlock

> [22:31:43 INFO]: Verze: 2.5.0-SNAPSHOT

> [22:31:43 INFO]: Popis: Ultimate SkyBlock v${gitTag}-DEV-dev

> [22:31:43 INFO]: Jazyk: cs (cs)

> [22:31:43 INFO]: ------------------------------

> [22:31:43 INFO]: Server: CraftBukkit git-Spigot-db6de12-18fbb24 (MC: 1.8.8)

> [22:31:43 INFO]: ------------------------------

> [22:31:43 INFO]: Název: Vault (ENABLED)

> [22:31:43 INFO]: Verze: 1.5.6-b49

> [22:31:43 INFO]: ------------------------------

> [22:31:43 INFO]: Název: WorldEdit (ENABLED)

> [22:31:43 INFO]: Verze: 6.1;no_git_id

> [22:31:43 INFO]: ------------------------------

> [22:31:43 INFO]: Název: WorldGuard (ENABLED)

> [22:31:43 INFO]: Verze: 6.1

> [22:31:43 INFO]: ------------------------------

> [22:31:43 INFO]: Název: AsyncWorldEdit (ENABLED)

> [22:31:43 INFO]: Verze: 2.2.2

> [22:31:43 INFO]: ------------------------------

ERROR

> [22:23:59 ERROR]: null

org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.5.0-SNAPSHOT

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]

	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]

	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

Caused by: java.lang.NullPointerException

	at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.addMainMenu(SkyBlockMenu.java:465) ~[?:?]

	at us.talabrek.ultimateskyblock.menu.SkyBlockMenu.displayIslandGUI(SkyBlockMenu.java:399) ~[?:?]

	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:68) ~[?:?]

	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]

	... 15 more

**Comment by dutchy1001** [comment]
it looks like you are using a custom language file and the usb version is outdated as that version has a bug in it for the custom language setting. Try v2.5.4 and see if the problem still occurs if so revert to default English till there is a better fix.
