### ISSUE TITLE
/island restart fix Cauldron

### ISSUE THREAD

**Issue by hunter688** [rlf/uSkyBlock#575]
Please fix bukkit-1.7.9 branch with this patch:

<pre>
diff --git a/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/async/IncrementalRunnable.java b/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/async/IncrementalRunnable.java
index 7b87dbe..f99785f 100644
--- a/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/async/IncrementalRunnable.java
+++ b/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/async/IncrementalRunnable.java
@@ -163,7 +163,7 @@ public abstract class IncrementalRunnable extends BukkitRunnable {
         try {
             if (!execute() && !isCancelled) {
                 // TODO: 28/09/2015 - R4zorax: Don't run back to back ALL the time
-                Bukkit.getScheduler().runTaskLater(plugin, this, consecutiveRuns < maxConsecutive ? 0 : yieldDelay);
+                Bukkit.getScheduler().runTaskLater(plugin, (Runnable)this, consecutiveRuns < maxConsecutive ? 0 : yieldDelay);
             } else {
                 if (onCompletion != null && !isCancelled) {
                     Bukkit.getScheduler().runTaskLater(plugin, onCompletion, 0);
</pre>

This will fix issues with /island restart on the modded cauldron server.

Thanks

**Comment by hunter688** [comment]
Juust FYI without this patch get this exception on Cauldron:

<pre>
[17:01:30] [Server thread/WARN]: [uSkyBlock] Task #1359 for uSkyBlock v2.5.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.scheduler.BukkitScheduler.runTaskLater(Lorg/bukkit/plugin/Plugin;Lorg/bukkit/scheduler/BukkitRunnable;J)Lorg/bukkit/scheduler/BukkitTask;
        at us.talabrek.ultimateskyblock.async.IncrementalRunnable.run(IncrementalRunnable.java:166) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-MCPC-Plus-1.7.10-1.1566.06.225]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:347) [CraftScheduler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1566.06.225]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
</pre>

**Comment by rlf** [comment]
Please create a pull-request for it.
