### ISSUE TITLE
AsynWordEdit error

### ISSUE THREAD

**Issue by matthijs110** [rlf/uSkyBlock#588]
Hello,

Since people are generating an island, I am getting the following error spammed:
```
[16:37:01 WARN]: [AsyncWorldEdit] Task #58110 for AsyncWorldEdit v2.2.2 generated an exception
java.lang.NullPointerException
        at us.talabrek.ultimateskyblock.handler.asyncworldedit.PlayerJob.equals(PlayerJob.java:107) ~[?:?]
        at java.util.ArrayList.remove(Unknown Source) ~[?:1.8.0_60]
        at java.util.Collections$SynchronizedCollection.remove(Unknown Source) ~[?:1.8.0_60]
        at us.talabrek.ultimateskyblock.handler.asyncworldedit.AWE211Adaptor$1.disableMessage(AWE211Adaptor.java:84) ~[?:?]
        at org.primesoft.asyncworldedit.progressDisplay.ProgressDisplayManager.disableMessage(ProgressDisplayManager.java:75) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.hideProgressBar(BlockPlacer.java:883) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.fetchBlocks(BlockPlacer.java:418) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:339) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:296) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:69) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:206) ~[?:?]
        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_server.jar:git-Spigot-5f38d38-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
```

**Comment by rlf** [comment]
Please include info from `/usb version`

**Comment by dutchy1001** [comment]
no furter input, closing this
