### ISSUE TITLE
Cannot load plugins\uSkyBlock\lastIslandConfig.yml

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#657]
[06:18:03 ERROR]: Cannot load plugins\uSkyBlock\lastIslandConfig.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '
 ' (0x0) special characters are not allowed
in "'string'", position 0
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
nfiguration.java:57) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguratio
n.java:226) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguratio
n.java:169) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Yam
lConfiguration.java:180) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at us.talabrek.ultimateskyblock.uSkyBlock.reloadLastIslandConfig(uSkyBlo
ck.java:803) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.uSkyBlock.getLastIslandConfig(uSkyBlock.
java:813) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.uSkyBlock$2.run(uSkyBlock.java:235) [uSk
yBlock.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java
:71) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
23) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not
 allowed
        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.ja
va:67) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47) ~
[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[craftbukkit.jar:git-Spi
got-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
nfiguration.java:55) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
        ... 13 more

**Comment by swan201** [comment]
Change Ecording or check your config file

**Comment by rlf** [comment]
Or just delete the `lastIslandConfig.yml` and restart the plugin/server.

The lastIsland is only used for performance reasons - the plugin should be able to work without it (on next create, it will just start scanning from 0,0 - which might take some time - but should work).
