### ISSUE TITLE
1.7.10 - challenges.yml unacceptable character

### ISSUE THREAD

**Issue by Tencao** [rlf/uSkyBlock#738]
So, I'm constantly getting an error every boot regarding the challenges.yml, even completely freshly generated files. 

The error can be found below
`[12:57:23] [Server thread/ERROR]: Unable to read config file plugins\uSkyBlock\challenges.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xFFFD) special characters are not allowed
in "<string>", position 3077
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[YamlConfiguration.class:1.7.10-1614.56]
	at us.talabrek.ultimateskyblock.utils.yml.YmlConfiguration.loadFromString(YmlConfiguration.java:31) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[FileConfiguration.class:1.7.10-1614.56]
	at us.talabrek.ultimateskyblock.utils.file.FileUtil.readConfig(FileUtil.java:61) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.utils.file.FileUtil.getYmlConfiguration(FileUtil.java:138) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1154) [uSkyBlock.jar:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:216) [uSkyBlock.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1614.56]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.56]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:371) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50) ~[StreamReader.class:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:399) ~[Yaml.class:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[YamlConfiguration.class:1.7.10-1614.56]
	... 19 more
[12:57:23] [Server thread/INFO]: Moving existing config challenges.yml to backup/challenges-20160514-1257.yml`

**Comment by SgtLegoTown** [comment]
looks like a config error did you have tried to use the following link : [http://yaml-online-parser.appspot.com/](url)

**Comment by Tencao** [comment]
@SgtLegoTown That link returns a 404

**Comment by SgtLegoTown** [comment]
my fault : http://yaml-online-parser.appspot.com/

unacceptable character '?' (0xFFFD) special characters are not allowed in "<string>", position 3077

you have custom challenges ? can you five more information like when it happend after a update of the file maybe ?

**Comment by Tencao** [comment]
The file is completely untouched, raw generated by the plugin. I tried making changes and searching for any special characters, but I cant find any. 

http://pastebin.com/8Tuv8g3k

The link above is the yml that triggered the error.

**Comment by SgtLegoTown** [comment]
can you paste your usb v for some extra information

**Comment by Tencao** [comment]
Name: uSkyBlock
Version: 2.5.3-bukkit-1.7.9
Description: Ultimate SkyBlock v2.5.3-bukkit-1.7.9-da7f04-383
Language: en (en)
------------------------------
Server: Cauldron 1.7.10-1614.56 (MC: 1.7.10)
------------------------------
Name: Vault (ENABLED)
Version: 1.4.1-b436
------------------------------
Name: WorldEdit (ENABLED)
Version: 6.1;no_git_id
------------------------------
Name: WorldGuard (ENABLED)
Version: 6.1
------------------------------

**Comment by SgtLegoTown** [comment]
Cauldron I cant support because I don't know anything about it 
only see in my config #[color code] The color to use for uncompleted challenges in the list.
challengeColor: §e and something different in yours. but since I don't have any 1.7. or Cauldron
test server I cant test it ..

I hope dutchy or r4z can help you

**Comment by Tencao** [comment]
I just want to add, everything else in cauldron seems to be working, except the challenges. Also the block icons are all dirt blocks, but that could be related to it not reading from the yml, and may just fix itself once the yml is also fixed.

**Comment by dutchy1001** [comment]
Cauldron or any fork of it isn't supported.
Every time a different Cauldron issue appears is probably caused due the many addons that are used.
I'm sorry this is happening but I wont spend any (more) time to solve these Cauldron issue's as I tried in the past many times to get it working on my pc which failed every time.

**Comment by Tencao** [comment]
It's a shame to see that help was outright refused rather than at least try to resolve this issue. In the end, the issue was resolved by me directly copying the challenges.yml from the jar itself, rather than let the mod copy the file. I'm only putting this here as a solution to those who experience something similar.

**Comment by dutchy1001** [comment]
Why a shame?? I explained  why I don't support it. How would you test things if you can't get it to work in the first place? I have spend many days to get a client working with Cauldron without success.

We haven't outright refused support, we tried but due to all different issue's it causes we can't keep going back to a server version that is almost 2 years old (1.7.10 was released June 26, 2014). 
Why don't al the server owners that uses Cauldron not banging on the door of the guys that make Cauldron to update there stuff instead of complaining that plugins/mods don't work any more with the new versions?

**Comment by Tencao** [comment]
The thing is, I have gone to cauldron devs just as much as plugin devs about issues regarding cauldron, but before that can happen, it's important to know the source of the problem, as sometimes a unique plugin setup can cause just as much problems as using cauldron. Anyway, the reason I said support was outright refused was because while you wasn't able to offer support directly via testing, you could have easily just asked me if I was able to get it working on a regular spigot server, and if it only breaks when switching to cauldron, or even what I ended up doing to fix it, instead of just closing the ticket. I will already be making a ticket on Thermos (the cauldron version I'm using) requesting them to fix this kind of bug, but as much as I don't want to unnecessarily bother plugin devs with cauldron specific issues, I also don't want to bother cauldron with a plugin specific issues, so it's important to know the source of the problem so I know where to go, and usually it's a guessing game based on the error I get. 

Anyway, the issue is now resolved, and I'll be taking this information to the cauldron devs in hopes they fix it their end.

**Comment by SgtLegoTown** [comment]
how many cauldron version are there ?  ... do I need to say more and a lot of servers are still running the usyblock plugin so I find it hard to believe then that the USB is broke when I know its running on over a 1000 servers .. I think a cause of trying to go forward instead of staying still and going backwards.
and ofcourse there will be bugs but I still find dutchy and r4z one of them most patient dev supports I know. There always willing to help anybody. It would be nice if ppl would report problems or bugs with the information where is asked for on the website like versions and a pastbin with the errors. and maybe with a little luck read before they put a plugin in there server. Because its very well documented .. its no a guessing game I think more using good logic and try to read in ..

**Comment by Tencao** [comment]
There's mods out there also running on over 1000 clients, yet all it takes is just one to find a bug. I don't want to continue this any further than it has, as the problem is resolved, and the issue has been forwarded to the Thermos team who's currently looking into the issue.

**Comment by rlf** [comment]
The `0xFFFD` is indicating, that the file is not a "proper UTF-8 encoded text-file".
See http://www.fileformat.info/info/unicode/char/fffd/index.htm

In other words, the challenges.yml has been edited in an editor that do not understand UTF-8.

Do so, and it should work.
