### ISSUE TITLE
Console spamming issue

### ISSUE THREAD

**Issue by MythixDino** [rlf/uSkyBlock#752]
Hi

I don't know how to fix this, so please help?
This error just keep spamming the console and thus it also creates big logs.
Note: Using the latest 1.7.9 version (Modded server).

[Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to uSkyBlock v2.5.3-bukkit-1.7.9
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.56]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.56]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.56]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223) [CraftEventFactory.class:1.7.10-1614.56]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:250) [ForgeEventFactory.class:1.7.10-1614.56]
	at cofh.thermalexpansion.block.device.TileActivator.simRightClick(TileActivator.java:371) [TileActivator.class:?]
	at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:189) [TileActivator.class:?]
	at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:148) [TileActivator.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2580) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: us.talabrek.ultimateskyblock.guava.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key c1fc3ace-e6b2-37ed-a575-03e0d777d7f1.
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2350) ~[?:?]
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.loadSync(LocalCache.java:2320) ~[?:?]
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[?:?]
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[?:?]
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache.get(LocalCache.java:3937) ~[?:?]
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[?:?]
	at us.talabrek.ultimateskyblock.guava.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[?:?]
	at us.talabrek.ultimateskyblock.player.PlayerLogic.getPlayerInfo(PlayerLogic.java:137) ~[?:?]
	at us.talabrek.ultimateskyblock.player.PlayerLogic.getPlayerInfo(PlayerLogic.java:127) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.locationIsOnIsland(uSkyBlock.java:773) ~[?:?]
	at us.talabrek.ultimateskyblock.uSkyBlock.playerIsOnIsland(uSkyBlock.java:737) ~[?:?]
	at us.talabrek.ultimateskyblock.event.PlayerEvents.onClickOnObsidian(PlayerEvents.java:121) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.56]
	... 15 more

**Comment by SgtLegoTown** [comment]
please provide more information like /usb v

**Comment by rlf** [comment]
See issue #662
