### ISSUE TITLE
Task #15 for uSkyBlock v2.6.4 generated an exception

### ISSUE THREAD

**Issue by PinoyLifeCraft** [rlf/uSkyBlock#760]
[21:33:45 WARN]: [uSkyBlock] Task #15 for uSkyBlock v2.6.4 generated an exceptio
n
java.lang.NullPointerException
        at com.sk89q.worldguard.bukkit.RegionContainer.get(RegionContainer.java:
236) ~[?:?]
        at com.sk89q.worldguard.protection.GlobalRegionManager.get(GlobalRegionM
anager.java:78) ~[?:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGu
ardPlugin.java:976) ~[?:?]
        at us.talabrek.ultimateskyblock.handler.WorldGuardHandler.setupGlobal(Wo
rldGuardHandler.java:320) ~[?:?]
        at us.talabrek.ultimateskyblock.uSkyBlock$2.run(uSkyBlock.java:261) ~[?:
?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java
:71) ~[craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
34) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [craftbukkit.jar:git-Spigot-8a048fe-71e5248]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]

**Comment by dutchy1001** [comment]
no output of **/usb version** or any other info.
This is not the way to post an issue.
