### ISSUE TITLE
Invite and topten problem

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#887]
When i write is invite there is a problem happening. Also when i use /is topten [uSkyBlock] Error during rank generation spamming. But when i downgrade to 2.7.2 the problem is solving.

USB Version:
[13:12:30 INFO]: Name: uSkyBlock
[13:12:30 INFO]: Version: 2.7.3-alpha7
[13:12:30 INFO]: Description: Ultimate SkyBlock v2.7.3-alpha7-367c72-441
[13:12:30 INFO]: Language: tr (tr)
[13:12:30 INFO]:   State: d=110, r=52, i=155,223, p=246,015, n=false, awe=false
[13:12:30 INFO]: Server: CraftBukkit git-PaperSpigot-"8b18730" (MC: 1.8.8)
[13:12:30 INFO]:   State: online=false, bungee=false
[13:12:30 INFO]: ------------------------------
[13:12:30 INFO]: Vault 1.5.6-b49 (ENABLED)
[13:12:30 INFO]: WorldEdit 6.1.3;7a097ca (ENABLED)
[13:12:30 INFO]: WorldGuard 6.1.2;e38d98d (ENABLED)
[13:12:30 INFO]: Multiverse-Core 2.5-b717 (ENABLED)
[13:12:30 INFO]: Multiverse-NetherPortals 2.5-b675 (ENABLED)
[13:12:30 INFO]: ------------------------------

Logs:
`[13:11:58 ERROR]: Could not pass event InviteEvent to uSkyBlock v2.7.3-alpha7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot.jar:git-PaperSpigot-"8b18730"]
        at us.talabrek.ultimateskyblock.command.island.InviteCommand.doExecute(InviteCommand.java:58) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:43) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:123) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.utils.command.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:38) [uSkyBlock.jar:?]
        at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:88) [uSkyBlock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
`

Latest log: https://www.uniocraft.com/latest.log

**Comment by rlf** [comment]
Most likely related to offline and UUID (perhaps invalid/corrupt data).

Try to backup your `uuid2name.yml` file, delete it, and restart the plugin - if this resolves the nullpointer exceptions, that is the cause.

**Comment by UnioDex** [comment]
Probably. I still using 2.0 BETA Skyblock with players.yml. I want to update. My server is in offline mode.  When i trying to make UUID update player names are seeing null.

**Comment by dutchy1001** [comment]
Isn't that a prehistoric version from before we took over??

**Comment by UnioDex** [comment]
Yes it is. The server is exist about 2 years.

**Comment by UnioDex** [comment]
When i remove uuid2name.yml the problem seems solved.
