### ISSUE TITLE
MemberLeftEvent exception

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#899]
This is my MemberLeftEvent code
```java
`	  @EventHandler
	  public void AdadanCikinca(MemberLeftEvent event){
		  BukkitScheduler scheduler = getServer().getScheduler();
		  scheduler.scheduleSyncDelayedTask(this, new Runnable() {
			  @Override
			  public void run() {
				  Player p = event.getPlayerInfo().getPlayer();
				  String pname = p.getName();
				  if (permission.playerInGroup(p, "Moderator")) {
					  return;
				  }else {
					  Bukkit.getServer().dispatchCommand(Bukkit.getServer().getConsoleSender(), "perm player " + pname + " removegroup SkyLord");
					  Bukkit.getServer().dispatchCommand(Bukkit.getServer().getConsoleSender(), "perm player " + pname + " removegroup SkyDuke");
					  Bukkit.getServer().dispatchCommand(Bukkit.getServer().getConsoleSender(), "perm player " + pname + " removegroup SkyKing");
					  Bukkit.getServer().dispatchCommand(Bukkit.getServer().getConsoleSender(), "perm player " + pname + " removegroup SkyGod");
				  }
			  }
		  }, 1L);
	  }`
```
When members are left i have this error in my console: 

```
[17:27:15 WARN]: [USB2] Task #1142 for USB2 v2.0-SNAPSHOT generated an exception
java.lang.NullPointerException
        at net.uniodex.USB2.Main$3.run(Main.java:718) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"8b18730"]

```

**Comment by rlf** [comment]
This is not caused by uSkyBlock - but entirely by your own code.

The very first line after NullPointerException tells you exactly what line the error occurred, and what it was about.

**Comment by rlf** [comment]
On a sidenote - you can probably accomplish what you want, simply by using the configuration options in uSkyBlock, see:
https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/config.yml#L238
I.e.
```yml
  extra-commands:
    - perm player {player} removegroup SkyLord
    - perm player {player} removegroup SkyGod
   ...
```

**Comment by UnioDex** [comment]
Line 59 (where it print error) is:
`String pname = event.getPlayerInfo().getPlayer().getName();`
There is an error in getting player info.

There is a condition in my commands. If player is in Moderator group i dont want to use extra commands. I wrote that for this. If you can add conditions (like if player is op or if player has permission or etc.) to extra-commands i will use extra-commands section.

**Comment by rlf** [comment]
But, that is your code, and hence your code is the one failing.
It's normally a good idea, to add sane-checking when doing what you are doing there, either:
1. `getPlayerInfo()` returns `null` (which it might do?)
2. `getPlayer()` returns `null` which it will do if the player is offline, i.e. kicked while offline

But hey, I don't have time treating your bad coding, as an issue with uSkyBlock.
That is why I closed it.
