### ISSUE TITLE
PlayerMoveEvent problem

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#919]
/usb version:
[16:36:48 INFO](------------------------------): Name: uSkyBlock
[16:36:48 INFO](------------------------------): Version: 2.7.3-alpha7
[16:36:48 INFO](------------------------------): Description: Ultimate SkyBlock v2.7.3-alpha7-367c72-441
[16:36:48 INFO](------------------------------): Language: tr (tr)
[16:36:48 INFO](------------------------------):   State: d=160, r=80, i=4,752, p=4,784, n=false, awe=false
[16:36:48 INFO](------------------------------): Server: CraftBukkit git-TacoSpigot-"c80c1e5" (MC: 1.8.8)
[16:36:48 INFO](------------------------------):   State: online=true, bungee=true

[16:36:48 INFO](------------------------------): Vault 1.5.6-b49 (ENABLED)
[16:36:48 INFO](------------------------------): WorldEdit 6.1.3;7a097ca (ENABLED)
[16:36:48 INFO](------------------------------): WorldGuard 6.1 (ENABLED)
[16:36:48 INFO](------------------------------): Multiverse-Core 2.5-b717 (ENABLED)
[16:36:48 INFO](------------------------------): Multiverse-NetherPortals maven-version-number (WRONG-VERSION)

[16:35:41 ERROR]: Could not pass event PlayerMoveEvent to uSkyBlock v2.7.3-alpha7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException

I dont know why is this happening but i saw it in my console and i wanted to write that.

**Comment by dutchy1001** [comment]
Is it an error that keeps poppin up or just once? If once then disregard this as a glitch. 
You also have a wrong depended plugin for the MV-NetherPortals ((WRONG-VERSION) is indicating this), that could also cause an error, not saying this is related but it could.

**Comment by UnioDex** [comment]
I edited MV-NetherPortals plugin for that issue Multiverse/Multiverse-NetherPortals#118 

I will make more test to find out why this error happening.

**Comment by UnioDex** [comment]
Problem is continuing. Today i had 500 MB logs full of Nullpointerexception.

500 MB logs (compressed 3mb, i can open with Notepad++):
https://www.dropbox.com/s/04hz465xz56g4w2/latest.log.tar.gz?dl=0

Spammed Exception:
http://pastebin.com/x6hsWhRs

**Comment by UnioDex** [comment]
I couldnt find the reason but im tired of 1GB logs everyday. I cant check my logs because of this error.

**Comment by dutchy1001** [comment]
I'm sorry this is happening but I would recommend to add Multivers-Portals and use an original Multivers-NetherPortals.
I hear you say it's that that is not the issue but if you don't try you will never know. Send me a log were those plugins are added with the errors showing then we can rule out that cause.
As long you don't use the recommended dependencies we cannot guarantee the correct working of the plugin.
As nobody else is complaining that this issue in this extend is on their servers (and believe me they would complain) I'm almost sure that the cause is not uSkyblock but caused due to an other plugin.

You could use the next alpha build [here](https://github.com/rlf/uSkyBlock/releases/tag/v2.7.3-alpha9) and see if that makes a differance.

I never have used TacoSpigot which also could be a cause, try PaperSpigot or even normal Spigot to rule those versions out too.

**Comment by rlf** [comment]
@UnioDex this (and most of the other issues you have been experiencing), is caused by you using offline mode, and having errorneous entries in the `name2uuid.yml` file.

A work-around could be, to somehow disable the use of our player-database (i.e. making all calls go directly to the `Bukkit.getPlayer`), this will most likely remove the NullPointerExceptions, but most certainly lead to performance issues.

**Comment by UnioDex** [comment]
@rlf you should add a warning in landing page like: "Dont use this plugin if your server is offline mode. When you notice a bug to us we will always excuse it." And i wouldnt open my server with that plugin.

**Comment by UnioDex** [comment]
@rlf you should add a warning in landing page like: "Dont use this plugin if your server is offline mode. When you notice a bug to us we will always excuse it." And i wouldnt open my server with that plugin.

**Comment by dutchy1001** [comment]
I don't think we have to state that offline servers "could" have issue's, any server, offline or online, can have issue's all depending on many other things. There are plenty offline servers using this without any issue. If this was the case you wouldn't be the only one complaining.
Like I said in one of my previous messages, have you done any of those suggestions to see if that helped?

**Comment by UnioDex** [comment]
Yes. Im using PaperSpigot, im using the original MVNetherPortals but it is not solved. But i didnt try changing my online-mode=false part to online-mode=true.

As @rlf said that this is about using offline mode. I dont understand why this error about using offline mode.

**Comment by BlackBeltPanda** [comment]
Happening for me now with an online-mode server: #934

**Comment by rlf** [comment]
For performance reasons we tried to introduce a caching of the player-name-2-uuids.
In the first "version" this was made as a yml-file, unfortunately, the libraries for accessing yml files are not thread-safe, meaning this is a shitty platform for that sort of data.

The very-short-term-solution is to delete the `name2uuid.yml` file and reload (`/usb reload`).
The short-term-solution is to introduce a way to circumvent the yml-file (i.e. asking Bukkit directly, this will introduce a performance penalty).
The long-term-solution is to move the "database" into a database-format (SQLite and/or MySQL).

I have had a lot of other priorities, and have done next to no development on uSkyBlock for a couple of months - so unfortunately - there is no ETA on this issue. Perhaps I will find some time during Christmas... perhaps.
