### ISSUE TITLE
Vault problems

### ISSUE THREAD

**Issue by iZerus** [rlf/uSkyBlock#931]
------------------------------
Server: KCauldron 1.7.10-1492.152 (MC: 1.7.10)
------------------------------
Name: Vault (N/A§d)
Version: 1.5.6-b49
------------------------------
Name: WorldEdit (N/A§d)
Version: 6.0;3342-78f975b9
------------------------------
Name: WorldGuard (N/A§d)
Version: 6.1
------------------------------

_What steps will reproduce the problem?_
1. Click island level

[09:45:44 INFO]: Player1234 issued server command: /is
[09:45:45 WARN]: Exception in thread "Craft Scheduler Thread - 108"
[09:45:45 WARN]: org.apache.commons.lang.UnhandledException: Plugin uSkyBlock v2.5.3-bukkit-1.7.9 generated an exception while executing task 1929
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.milkbowl.vault.item.Items
        at us.talabrek.ultimateskyblock.handler.VaultHandler.getItemName(VaultHandler.java:74)
        at us.talabrek.ultimateskyblock.island.BlockScoreImpl.<init>(BlockScoreImpl.java:24)
        at us.talabrek.ultimateskyblock.island.BlockScoreImpl.<init>(BlockScoreImpl.java:16)
        at us.talabrek.ultimateskyblock.island.LevelLogic.createIslandScore(LevelLogic.java:267)
        at us.talabrek.ultimateskyblock.island.LevelLogic$1.run(LevelLogic.java:179)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by dutchy1001** [comment]
Use vault 1.4.1
Cauldron is not furter supported
