### ISSUE TITLE
is level name error

### ISSUE THREAD

**Issue by andris155** [rlf/uSkyBlock#967]
uSkyBlock v2.7.3-alpha16 + Paper 1.11
```
[13:00:26] [Server thread/INFO]: poma123 issued server command: /is level asdlol911
[13:00:26] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.7.3-alpha16
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1375) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1180) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-976]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-976]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.command.island.LevelCommand$1.run(LevelCommand.java:73) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.getIslandLevel(LevelCommand.java:93) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.doExecute(LevelCommand.java:44) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:43) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:123) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.command.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:38) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:88) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.11.jar:git-Paper-976]
	... 15 more
[13:01:03] [Server thread/INFO]: poma123 issued server command: /is level asdlol911
[13:01:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.7.3-alpha16
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.11.jar:git-Paper-976]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1375) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1180) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.jar:git-Paper-976]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-976]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-976]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.command.island.LevelCommand$1.run(LevelCommand.java:73) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.getIslandLevel(LevelCommand.java:93) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.doExecute(LevelCommand.java:44) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:43) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:123) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.command.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:38) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:88) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.11.jar:git-Paper-976]
	... 15 more
```

**Comment by dutchy1001** [comment]
Pls follow the template when creating a bug report for the info we need
