### ISSUE TITLE
/is level playername error

### ISSUE THREAD

**Issue by andris155** [rlf/uSkyBlock#968]
_Please paste the output from `/usb version` below_
```
24.01 15:39:04 [Server] INFO Name: uSkyBlock
24.01 15:39:04 [Server] INFO Version: 2.7.3-alpha16
24.01 15:39:04 [Server] INFO Description: Ultimate SkyBlock v2.7.3-alpha16-08f268-451
24.01 15:39:04 [Server] INFO Language: en (en)
24.01 15:39:04 [Server] INFO State: d=128, r=64, i=795, p=871, n=false, awe=true
24.01 15:39:04 [Server] INFO Server: Paper git-Paper-976 (MC: 1.11)
24.01 15:39:04 [Server] INFO State: online=true, bungee=true
24.01 15:39:04 [Server] INFO ------------------------------
24.01 15:39:04 [Server] INFO Vault 1.5.6-b49 (ENABLED)
24.01 15:39:04 [Server] INFO WorldEdit 6.1.5;4651611 (ENABLED)
24.01 15:39:04 [Server] INFO WorldGuard 6.2.1-SNAPSHOT;1695-6e56763 (ENABLED)
24.01 15:39:04 [Server] INFO AsyncWorldEdit 3.4.8 (ENABLED)
24.01 15:39:04 [Server] INFO Multiverse-Core 2.5-b719 (ENABLED)
24.01 15:39:04 [Server] INFO Multiverse-Portals 2.5.0-SNAPSHOT-b748 (ENABLED)
24.01 15:39:04 [Server] INFO Multiverse-NetherPortals 2.5.0-SNAPSHOT-b714 (ENABLED)
24.01 15:39:04 [Server] INFO ------------------------------
```

_What steps will reproduce the problem?_
1. /is level playername

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
http://pastebin.com/FsXcJhJn

**Comment by UnioDex** [comment]
I have exact same issue with 1.8 spigot and 2.7.3-alpha16.
`[05:40:52] [Server thread/INFO]: WoodyPrime issued server command: /is level GoldenMachete
[05:40:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin uSkyBlock v2.7.3-alpha16
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at us.talabrek.ultimateskyblock.command.island.LevelCommand$1.run(LevelCommand.java:73) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.getIslandLevel(LevelCommand.java:93) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.LevelCommand.doExecute(LevelCommand.java:44) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequireIslandCommand.doExecute(RequireIslandCommand.java:43) ~[?:?]
	at us.talabrek.ultimateskyblock.command.island.RequirePlayerCommand.execute(RequirePlayerCommand.java:32) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.command.CompositeCommand.execute(CompositeCommand.java:123) ~[?:?]
	at us.talabrek.ultimateskyblock.utils.command.AbstractCommandExecutor.onCommand(AbstractCommandExecutor.java:38) ~[?:?]
	at us.talabrek.ultimateskyblock.command.IslandCommand.onCommand(IslandCommand.java:88) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	... 15 more`
